
<!DOCTYPE html>

<html class="html" lang="en-US">
<head>

    <!-- jQuery library -->
    <script src="/templates/assets/js/jquery.2.1.3.min.js" type="text/javascript"></script>
    <script src="/templates/assets/js/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
    <script src="/templates/assets/js/jquery.scrollbar.js"></script>

    <meta http-equiv="Content-type" content="text/html;charset=UTF-8"/>

    <title>WALK FUNDS - Official web page</title>
    <!-- icos -->
    <link href="/templates/images/57.jpg" rel="apple-touch-icon" sizes="57x57"/>
    <link href="/templates/images/114.jpg" rel="apple-touch-icon" sizes="114x114"/>
    <link href="/templates/images/72.jpg" rel="apple-touch-icon" sizes="72x72"/>
    <link href="/templates/images/144.jpg" rel="apple-touch-icon" sizes="144x144"/>
    <link href="/templates/images/60.jpg" rel="apple-touch-icon" sizes="60x60"/>
    <link href="/templates/images/120.jpg" rel="apple-touch-icon" sizes="120x120"/>
    <link href="/templates/images/76.jpg" rel="apple-touch-icon" sizes="76x76"/>
    <link href="/templates/images/152.jpg" rel="apple-touch-icon" sizes="152x152"/>
    <link href="/templates/images/180.jpg" rel="apple-touch-icon" sizes="180x180"/>
    <link href="/templates/images/fav192.jpg" rel="icon" sizes="192x192" type="image/jpg"/>
    <link href="/templates/images/fav160.jpg" rel="icon" sizes="160x160" type="image/jpg"/>
    <link href="/templates/images/fav96.jpg" rel="icon" sizes="96x96" type="image/jpg"/>
    <link href="/templates/images/fav32.jpg" rel="icon" sizes="32x32" type="image/jpg"/>
    <link style="border-radius:4px;" href="apple/fav16.jpg" rel="icon" sizes="16x16" type="image/jpg"/>
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="/templates/css/site_global.css"/>
    <link rel="stylesheet" type="text/css" href="/templates/css/index.css" id="pagesheet"/>
    <link rel="stylesheet" type="text/css" href="/templates/css/my.css" id="pagesheet"/>
    <!--[if lt IE 9]>
    <link rel="stylesheet" type="text/css" href="css/iefonts_index.css?196463317"/>
    <![endif]-->
    <!-- Other scripts -->

    <link href='https://fonts.googleapis.com/css?family=Roboto:900,400,300,100,700&amp;subset=cyrillic-ext,latin' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/templates/css/morris.css">
    <!--[if lt IE 9]>
    <script src="/js/ie.html5.js?4241844378" type="text/javascript"></script>
    <![endif]-->
    <style>
        .clinkedcolors{color:#2B6F98 !important;
            border-bottom:1px dashed #484848;}
    </style>

    <script src="/templates/js/plugin.acc.js" type="text/javascript"></script>
    <script src="/templates/js/plugin.progress.js" type="text/javascript"></script>

    <script src="/templates/js/morris.js"></script>
    <script src="/templates/js/javascript22c1.js?4241844378" type="text/javascript"></script>

    <audio id="audio-notify" controls="controls" preload="auto">
        <source src="audio/notify.html"></source>
        <source src="audio/notify-2.html"></source>
    </audio>


</head>
<body>

<div class="alertb">

    <a href="#" id="notifies" class="alert-o">
        <span class="popamount"><span class="notifycount">0</span></span>
    </a>


    <span id="notifies_block" class="intern" style = "display:none" >


<div class="tooltipy2 bottom in2 poppad">

<div class="bgpop"></div>

<div class="tooltip-inner2">


<div class="nonews">
	<div class="nonews_block">No more notifications</div>
	<img src="../ssl.gstatic.com/s2/oz/images/notifications/jingles_eb4e5306b38f83915d82034fa93390d9/desktop_static_1x.png" alt="*" class="axb m4a"/>
</div>


<div class="yesnews">

<div style="width:100%; text-align: left;margin-bottom: 5px;"><div style="text-transform:uppercase;font-size:13px;font-weight:300;color: #494949;">You have <b><span class="notifycount">0</span></b> new notifications</div>
</div>
<div class="fixedheight scrollbar-inner">







</div>
<a href="#" id="closeall" class="butbut">Close all</a>
</div>
</div>
</div></span>
</div>



<div class="menubgin"><div style="width:940px; margin:0 auto; height:100%;">
        <a id="u107" href="?a=home" style=""></a>

        <div class="bgxs">
            <ul id="langbar">
                <li id="langbar" style="position: relative;height: 40px;" class="drop">

                    <a href="#" class="bgkx"><img style="margin: 0px 8px 0px -6px;" src="/templates/images/en.png">EN</a>

                </li>
            </ul>
        </div>

        <nav class="indiv menuu119"><!-- horizontal box -->
            <ul class="hr">
                <li><a  href="/">Home</a></li>
                <li><a  href="aboutus">About us</a></li>
                <li><a  href="features">Features</a></li>
                <li><a class="selected" href="faq">FAQ</a></li>
                <li><a  href="support">Feedback</a></li>
            </ul>

        </nav>


    </div></div><div class="shadow Featured-In clearfix" id="page">
    <!-- column -->


    <div class="browser_width colelem" id="u93-bw">
        <div class="u92x2"><!-- boxy -->
            <div class="clearfix" id="u93_align_to_page">
                <a class="anchor_item grpelem" id="features"></a>
            </div>
        </div>
    </div>

    <script src="js/nanobar.js"></script>
    <script>
        var nanobar = new Nanobar();
        nanobar.go(100);
    </script>

    <script>
        $( function()
        {
            var targets = $( '[rel~=tooltip]' ),
                target  = false,
                tooltip = false,
                title   = false;

            targets.bind( 'mouseenter', function()
            {
                target  = $( this );
                tip     = target.attr( 'title' );
                tooltip = $( '<div id="tooltip"></div>' );

                if( !tip || tip == '' )
                    return false;

                target.removeAttr( 'title' );
                tooltip.css( 'opacity', 0 )
                    .html( tip )
                    .appendTo( 'body' );

                var init_tooltip = function()
                {
                    if( $( window ).width() < tooltip.outerWidth() * 1.5 )
                        tooltip.css( 'max-width', $( window ).width() / 2 );
                    else
                        tooltip.css( 'max-width', 340 );

                    var pos_left = target.offset().left + ( target.outerWidth() / 2 ) - ( tooltip.outerWidth() / 2 ),
                        pos_top  = target.offset().top - tooltip.outerHeight() - 20;

                    if( pos_left < 0 )
                    {
                        pos_left = target.offset().left + target.outerWidth() / 2 - 20;
                        tooltip.addClass( 'left' );
                    }
                    else
                        tooltip.removeClass( 'left' );

                    if( pos_left + tooltip.outerWidth() > $( window ).width() )
                    {
                        pos_left = target.offset().left - tooltip.outerWidth() + target.outerWidth() / 2 + 20;
                        tooltip.addClass( 'right' );
                    }
                    else
                        tooltip.removeClass( 'right' );

                    if( pos_top < 0 )
                    {
                        var pos_top  = target.offset().top + target.outerHeight();
                        tooltip.addClass( 'top' );
                    }
                    else
                        tooltip.removeClass( 'top' );

                    tooltip.css( { left: pos_left, top: pos_top } )
                        .animate( { top: '+=10', opacity: 1 }, 50 );
                };

                init_tooltip();
                $( window ).resize( init_tooltip );

                var remove_tooltip = function()
                {
                    tooltip.animate( { top: '-=10', opacity: 0 }, 50, function()
                    {
                        $( this ).remove();
                    });

                    target.attr( 'title', tip );
                };

                target.bind( 'mouseleave', remove_tooltip );
                tooltip.bind( 'click', remove_tooltip );
            });
        });
    </script>

    <style>
        .margin-top24{
            margin-top:24px;}
        .hin{
            color: #258FD8 !important;
            border-bottom: dashed 1px;}
        .hin:hover {
            color: rgba(37, 143, 216, 0.65) !important;

        }
    </style>

    <div class="clearfix colelem" id="pu106-6">
        <!-- group -->

        <div style="text-align:center;" class="Heading-H1 clearfix mse_pre_init u106-6"><!-- content -->
            <h2 style="margin-bottom:15px;"><span class="animated fadeInUp" style="padding: 0 20px;">Questions and <b>Answers</b></span></h2>


        </div>
    </div>


    <div class="ppage">



        <div class="clearfix"></div>
        <div class="row">
            <style>
                .link9 {border-bottom: 1px dashed cadetblue;
                    color: cadetblue !important;}

                .balboos1 {
                    width: 15px;
                    height: 15px;
                    font-size: 10px;
                    border-radius: 20px;
                    margin-right: 9px;
                    margin-top: 0px;
                    cursor: pointer;
                    float: left;
                }
            </style>
            <script>
                $(function(){

                    var btn = $('.faqnav');
                    var btnPosTop = btn.offset().top;
                    var win = $(window);


                    win.scroll(function(e){
                        var scrollTop = win.scrollTop();
                        if(scrollTop >= btnPosTop){
                            btn.css({position:'fixed',top:0,marginTop:0,width:900});
                            $('.faq_block').eq(0).addClass('padding');
                        }else if(btn.css('position') === 'fixed'){
                            btn.css({position:'', width:'900'});
                            $('.faq_block').eq(0).removeClass('padding');
                        }
                    });

                    /*
                     $('.faqnav a').click(function(){
                     var id = $(this).attr('href');

                     $('.faq_block').removeClass('padding');
                     $(id).addClass('padding');

                     });
                     */

                    $('.faqnav a').click(function(){
                        var id = $(this).attr('href');
                        fix = 80;
                        $('html, body').stop().animate({scrollTop: $(id).offset().top - fix}, 800);

                        return false;
                    });


                });



            </script>

            <div class="row">
                <div style="width:100%;">

                    <div class="content">
                        <div class="wxz">
                            <div class="faqnav fix">Select an area
                                <a href="#genq" class="faqbut">Main</a>
                                <a href="#finq" class="faqbut" >Financial</a>
                                <a href="#afq" class="faqbut">Affiliate section</a>
                                <a href="#seq" class="faqbut">Safety</a>
                                <a href="#othq" class="faqbut">Other</a>
                            </div>

                            <div class="faq_block" id="genq">
                                <h3 style="text-align:center;text-transform:uppercase;margin-bottom: 44px;">Main</h3>
                                <div class="ptd">
                                    <div class="qxc">How to participate?</div>
                                    <div class="xzc">In order to participate, the participant must be 18 or older, then you must fill out <a class="link9" href="/customer/register"> registration form </a> necessary data and get started.</div>
                                </div>
                                <div class="ptd">
                                    <div class="qxc">How to start use an investment program?</div>
                                    <div class="xzc">First of all, carefully read all the sections related to the work with WALK FUNDS, necessary sections for review - <a class="link9" href="/aboutus"> About Us </a>, <a class = "link9" href = "/features "> especially </a>, <a class="link9" href="/terms"> terms of use and </a> section <a class="link9" href="/faq"> FAQs </ a>.</div>
                                </div>
                                <div class="ptd">
                                    <div class="qxc">What interest rate offers WALK FUNDS?</div>
                                    <div class="xzc">Our team developed a three-stage system of earnings. 10% Hourly 24hr, 15% Hourly 48hr, 20% Hourly 72hr</div>
                                </div>

                                <div class="ptd">
                                    <div class="qxc">How many days i can keep the main (principal) investment deposits?</div>
                                    <div class="xzc">Storage of main investment deposits can be from one to an unlimited number of days.</div>
                                </div>
                                <div class="ptd">
                                    <div class="qxc">Are you a HYIP or legal investment company?</div>
                                    <div class="xzc">We’re not a HYIP, we’re officially registered as an active existing company   	with its own capital and real partners all across the globe. Some of our   	partner companies are stated on our website. We are engaged in the   	investment activity, which can be based only on the principles of legality   	and good organization of business.<br><br>
                                        Is your main business on the Internet? <br><div class="botbon">Our main business is closely tied to the Internet but it’s not based there. When   we got to the idea that the Internet could be a good source for investments we   opened a special department responsible for the site exenest.com and all   investment activities associated with it. </div></div>
                                </div>
                                <div class="ptd">
                                    <div class="qxc">How long do you plan to stay in business?</div>
                                    <div class="xzc">There’s no reason which could limit the lifetime of our company. High   	technologies always bring money, so that we can see the future of our   	company for many many years. </div>
                                </div>

                                <div class="ptd">
                                    <div class="qxc">Your company invests into exenest.com, can you   	explain to me in short how it works?</div>
                                    <div class="xzc">The base of our business is the selection of promising venture projects   	that will be able to generate good incomes in less than three years. <br />
                                        <br />
                                        As soon as the venture project has been selected, we start negotiations with   	the venture company engaged in researching and development of   	exenest.com. Usually these companies are happy to deal with investors   	due to lack of governmental financing. This way they are ready to offer high   	percent returns soon after the project realization and its launch onto the   	market. <br />
                                        <br />
                                        Then we sign the agreement with the venture company and assign our project   	inspector to make sure the company spends these funds in a proper way. <br />
                                        <br />
                                        And finally, we convert electronic money of the payment systems and put   	these funds on our company's bank accounts, and then, we wire the money to   	the venture company's account.</div>
                                </div>
                            </div>

                            <div class="faq_block" id="finq">
                                <h3 style="text-align:center;text-transform:uppercase;margin-bottom: 44px;">Financial</h3>

                                <div class="ptd">
                                    <div class="qxc">What is the amount of investment needed to get started?</div>
                                    <div class="xzc">Our minimum amount of investment is <b> $ 20 </ b> and a maximum <b> $ 10,000 </b>.</div>
                                </div>
                                <div class="ptd">
                                    <div class="qxc">Can I make more than one payment?</div>
                                    <div class="xzc">We do not limit the number of investment deposits, you can make unlimited number of payments. The amount of investment deposits should not exceed <b> $ 10,000 </B></div>
                                </div>

                                <div class="ptd">
                                    <div class="qxc">What payment methods are available to make financial transactions?</div>
                                    <div class="xzc">The program provides an opportunity to make different methods of financial transactions. We work with payment systems, such as - <a class="link9" href="https://perfectmoney.is">Perfect Money</a>, <a class="link9" href="https://payeer.com">Payeer</a>, <a class="link9" href="https://bitcoin.org">Bitcoin</a></div>
                                </div>
                                <div class="ptd">
                                    <div class="qxc">Is it possible to deposit/withdraw and make any transactions with credit cards?</div>
                                    <div class="xzc">To do this, use the payment systems like - <a class="link9" href="https://payeer.com">Payeer</a>, where you can make financial transactions more than <b> 150 </ b> ways.</div>
                                </div>

                                <div class="ptd">
                                    <div class="qxc">How do I participate to make investment actions?</div>
                                    <div class="xzc">In order to create an investment deposit, you need to find in personal account  <a class="link9" href="/frontend/member/invest">Make deposit </a>, selecting the desired way to fund, enter the desired amount and payment system to carry out the investment deposit .</div>
                                </div>

                                <div class="ptd">
                                    <div class="qxc">How do I withdraw earned money?</div>
                                    <div class="xzc">In order to withdraw the earned funds, it's necessary in the personal account click on the <a class="link9" href="/frontend/member/history"> withdrawal section </a>, selecting an appropriate balance for withdrawal and payment system to perform withdrawals.</div>
                                </div>
                                <div class="ptd">
                                    <div class="qxc">How long does processing requests of deposit or withdrawal of funds?</div>
                                    <div class="xzc">All payments will be processed instantly.</div>
                                </div>

                                <div class="ptd">
                                    <div class="qxc">Having made an investment deposit with a payment system, it is capable of withdrawal on other e-currencies?</div>
                                    <div class="xzc">Withdrawal of the main investments is possible only on the payment system, which was used initially. Earnings, can be withdrawn on any of the available payment systems.</div>
                                </div>

                                <div class="ptd">
                                    <div class="qxc">How to leave and take the sum of the main (principal) investments?</div>
                                    <div class="xzc">In order to leave the program, you must put one of your active investment panels and start to gradually withdraw funds main investment.

                                        <br><br>1. Go into the details of the deposit<br><br>
                                        2. Notice the button - Close deposit by clicking on it, the deposit goes into output mode and will be displayed in real time, 24 hours.<br>
                                        <br>
                                        3. Withdrawal of funds that are available for payment.
                                        <br><br>
                                    </div>
                                </div>
                            </div>

                            <div class="faq_block" id="afq">
                                <h3 style="text-align:center;text-transform:uppercase;margin-bottom: 44px;">Affiliate section</h3>
                                <div class="ptd">
                                    <div class="qxc">What affiliate programs do you offer?</div>
                                    <div class="xzc">We offer a three levels of affiliate program with  3% - 1.5% - 1%</div>
                                </div>
                                <div class="ptd">
                                    <div class="qxc">Should I have an active deposit to earning referral commissions?</div>
                                    <div class="xzc">You do not need to have an active deposit to earn referral commissions.</div>
                                </div>
                                <div class="ptd">
                                    <div class="qxc">Where can i learn more about affiliate activities?</div>
                                    <div class="xzc">To get acquainted with the statistics of your partners, you can click in the account menu on   <a class="link9" href="/frontend/member">referral details</a>.</div>
                                </div>
                            </div>

                            <div class="faq_block" id="seq">
                                <h3 style="text-align:center;text-transform:uppercase;margin-bottom: 44px;">Safety</h3>
                                <div class="ptd">
                                    <div class="qxc">How to protect the personal account from unauthorized access?</div>
                                    <div class="xzc">Choose a password at least eight characters, the contents of which include - letters, numbers, symbols. Be sure to take care of the safety of personal data from third parties.</div>
                                </div>
                                <div class="ptd">
                                    <div class="qxc">Forgot account details to access, how to restore access?</div>
                                    <div class="xzc">You need to click on the link below - <a class="link9" href="/customer/resetpassword">Restore account data</a>.</div>
                                </div>
                                <div class="ptd">
                                    <div class="qxc">Forgot secret keyword to edit the profile, how to restore?</div>
                                    <div class="xzc">In case you forgot the secret keyword, contact a tech support for more information  about how to resolve that problem.</div>
                                </div>
                            </div>

                            <div class="faq_block" id="othq" >
                                <h3 style="text-align:center;text-transform:uppercase;margin-bottom: 44px;">Other</h3>
                                <div class="ptd">
                                    <div class="qxc">How does work Geno Finance's accrual system?</div>
                                    <div class="xzc">All accruals is working in real time.</div>
                                </div>


                                <div class="ptd">
                                    <div class="qxc">Are there any commissions when making a transactions?</div>
                                    <div class="xzc">We do not take any commission fees for any transactions.</div>
                                </div>

                                <div class="ptd">
                                    <div class="qxc">I have not found an answer to the question, what do I need to do?</div>
                                    <div class="xzc">Please contact tech support, know that you will get an instantly answer to your question.</div>
                                </div>
                            </div>


                        </div>
                    </div>
                </div>
            </div></div>

    </div>
</div>


</div><!-- column -->
<div class="clearfix"></div>
<div class="osd widj">

    <div class="footer" style="padding-bottom: 25px;"><!-- column -->
        <div class="clearfix" id="u320_align_to_page" style="padding: 20px 0;">

            <div style="display: inline-block;" class="Subheading-White clearfix colelem" id="u825-4"><!-- content -->
                <span style="display:inline-block; font-size: x-large">Accepting payment systems with
                        <img src='../templates/images/bt.png' style="width: 75px; height:25px;">
                    </span>
                <!--                <div style="padding: 22px 0px 0 140px;">-->
                <!--                    <div style="background:url('../templates/images/pm.png') no-repeat; width: 171px; height:50px;float:left;padding-right: 70px;"></div>-->
                <!--                    <div style="background:url('../templates/images/bt.png') no-repeat; width: 129px; height:50px;"></div>-->
                <!--                    <div style="background:url('../templates/images/pe.png') no-repeat; width: 253px; height:50px;float:left;top: 3px;position: relative;"></div>-->
                <!--                </div>-->
            </div>
        </div>
    </div>
    <div style="margin-top: -37px;"><!-- column -->
        <footer>

            <div class="footero">
                <div class="contain">
                    <div class="stpnw"><img width="170" src="templates/images/logo.png" class="instq"> © 2017
                    </div>
                    <div class="fixtd3">

                        <div style="padding: 2px 0px;"><a href="/" class="footerlink">Home</a></div>
                        <div style="padding: 2px 0px;"><a href="aboutus" class="footerlink">About us</a></div>
                        <div style="padding: 2px 0px;"><a href="support" class="footerlink">Feedback</a></div>

                    </div>



                    <div class="fixtd2">

                        <div style="padding: 2px 0px;"><a href="faq" class="footerlink">FAQ</a></div>
                        <div style="padding: 2px 0px;"><a href="terms" class="footerlink">Terms of use</a></div>

                    </div><div style=" position:relative; top: 25px; float: left; width: 110px; padding: 0 25px;">
                        <div style="padding: 2px 0px;"><a href="features" class="footerlink">Features</a></div>
                        <div style="padding: 2px 0px;"></div>

                    </div>


                    <div class="fixtd">

                        <div style="padding: 2px 0px;"><a href="#" class="footerlink">Adress: 207 NL. Lincoln Blvd. UK</a></div>
                        <div style="padding: 2px 0px;"><a href="#" class="footerlink">Phone: +447056105150</a></div>
                        <div style="padding: 2px 0px;"><a href="#" class="footerlink">walkfunds.com</a></div>

                    </div>
                </div>
            </div>
        </footer>
    </div>


</div>


</body>
</html>

