
<!DOCTYPE html>

<html class="html" lang="en-US">
<head>

    <!-- jQuery library -->
    <script src="/templates/assets/js/jquery.2.1.3.min.js" type="text/javascript"></script>
    <script src="/templates/assets/js/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
    <script src="/templates/assets/js/jquery.scrollbar.js"></script>

    <meta http-equiv="Content-type" content="text/html;charset=UTF-8"/>

    <title>WALK FUNDS - Official web page</title>
    <!-- icos -->
    <link href="/templates/images/57.jpg" rel="apple-touch-icon" sizes="57x57"/>
    <link href="/templates/images/114.jpg" rel="apple-touch-icon" sizes="114x114"/>
    <link href="/templates/images/72.jpg" rel="apple-touch-icon" sizes="72x72"/>
    <link href="/templates/images/144.jpg" rel="apple-touch-icon" sizes="144x144"/>
    <link href="/templates/images/60.jpg" rel="apple-touch-icon" sizes="60x60"/>
    <link href="/templates/images/120.jpg" rel="apple-touch-icon" sizes="120x120"/>
    <link href="/templates/images/76.jpg" rel="apple-touch-icon" sizes="76x76"/>
    <link href="/templates/images/152.jpg" rel="apple-touch-icon" sizes="152x152"/>
    <link href="/templates/images/180.jpg" rel="apple-touch-icon" sizes="180x180"/>
    <link href="/templates/images/fav192.jpg" rel="icon" sizes="192x192" type="image/jpg"/>
    <link href="/templates/images/fav160.jpg" rel="icon" sizes="160x160" type="image/jpg"/>
    <link href="/templates/images/fav96.jpg" rel="icon" sizes="96x96" type="image/jpg"/>
    <link href="/templates/images/fav32.jpg" rel="icon" sizes="32x32" type="image/jpg"/>
    <link style="border-radius:4px;" href="apple/fav16.jpg" rel="icon" sizes="16x16" type="image/jpg"/>
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="/templates/css/site_global.css"/>
    <link rel="stylesheet" type="text/css" href="/templates/css/index.css" id="pagesheet"/>
    <link rel="stylesheet" type="text/css" href="/templates/css/my.css" id="pagesheet"/>
    <!--[if lt IE 9]>
    <link rel="stylesheet" type="text/css" href="css/iefonts_index.css?196463317"/>
    <![endif]-->
    <!-- Other scripts -->

    <link href='https://fonts.googleapis.com/css?family=Roboto:900,400,300,100,700&amp;subset=cyrillic-ext,latin' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/templates/css/morris.css">
    <!--[if lt IE 9]>
    <script src="/js/ie.html5.js?4241844378" type="text/javascript"></script>
    <![endif]-->
    <style>
        .clinkedcolors{color:#2B6F98 !important;
            border-bottom:1px dashed #484848;}
    </style>

    <script src="/templates/js/plugin.acc.js" type="text/javascript"></script>
    <script src="/templates/js/plugin.progress.js" type="text/javascript"></script>

    <script src="/templates/js/morris.js"></script>
    <script src="/templates/js/javascript22c1.js?4241844378" type="text/javascript"></script>

    <audio id="audio-notify" controls="controls" preload="auto">
        <source src="audio/notify.html"></source>
        <source src="audio/notify-2.html"></source>
    </audio>


</head>
<body>

<div class="alertb">

    <a href="#" id="notifies" class="alert-o">
        <span class="popamount"><span class="notifycount">0</span></span>
    </a>


    <span id="notifies_block" class="intern" style = "display:none" >


<div class="tooltipy2 bottom in2 poppad">

<div class="bgpop"></div>

<div class="tooltip-inner2">


<div class="nonews">
	<div class="nonews_block">No more notifications</div>
	<img src="../ssl.gstatic.com/s2/oz/images/notifications/jingles_eb4e5306b38f83915d82034fa93390d9/desktop_static_1x.png" alt="*" class="axb m4a"/>
</div>


<div class="yesnews">

<div style="width:100%; text-align: left;margin-bottom: 5px;"><div style="text-transform:uppercase;font-size:13px;font-weight:300;color: #494949;">You have <b><span class="notifycount">0</span></b> new notifications</div>
</div>
<div class="fixedheight scrollbar-inner">







</div>
<a href="#" id="closeall" class="butbut">Close all</a>
</div>
</div>
</div></span>
</div>



<div class="menubgin"><div style="width:940px; margin:0 auto; height:100%;">
        <a id="u107" href="?a=home" style=""></a>

        <div class="bgxs">
            <ul id="langbar">
                <li id="langbar" style="position: relative;height: 40px;" class="drop">

                    <a href="#" class="bgkx"><img style="margin: 0px 8px 0px -6px;" src="/templates/images/en.png">EN</a>

                </li>
            </ul>
        </div>

        <nav class="indiv menuu119"><!-- horizontal box -->
            <ul class="hr">
                <li><a href="/">Home</a></li>
                <li><a  href="/aboutus">About us</a></li>
                <li><a  class="selected"  href="/features">Features</a></li>
                <li><a  href="/faq">FAQ</a></li>
                <li><a  href="/support">Feedback</a></li>
            </ul>

        </nav>


    </div></div><div class="shadow Featured-In clearfix" id="page">
    <!-- column -->


    <div class="browser_width colelem" id="u93-bw">
        <div class="u92x2"><!-- boxy -->
            <div class="clearfix" id="u93_align_to_page">
                <a class="anchor_item grpelem" id="features"></a>
            </div>
        </div>
    </div>

    <script src="js/nanobar.js"></script>
    <script>
        var nanobar = new Nanobar();
        nanobar.go(100);
    </script>

    <script>
        $( function()
        {
            var targets = $( '[rel~=tooltip]' ),
                target  = false,
                tooltip = false,
                title   = false;

            targets.bind( 'mouseenter', function()
            {
                target  = $( this );
                tip     = target.attr( 'title' );
                tooltip = $( '<div id="tooltip"></div>' );

                if( !tip || tip == '' )
                    return false;

                target.removeAttr( 'title' );
                tooltip.css( 'opacity', 0 )
                    .html( tip )
                    .appendTo( 'body' );

                var init_tooltip = function()
                {
                    if( $( window ).width() < tooltip.outerWidth() * 1.5 )
                        tooltip.css( 'max-width', $( window ).width() / 2 );
                    else
                        tooltip.css( 'max-width', 340 );

                    var pos_left = target.offset().left + ( target.outerWidth() / 2 ) - ( tooltip.outerWidth() / 2 ),
                        pos_top  = target.offset().top - tooltip.outerHeight() - 20;

                    if( pos_left < 0 )
                    {
                        pos_left = target.offset().left + target.outerWidth() / 2 - 20;
                        tooltip.addClass( 'left' );
                    }
                    else
                        tooltip.removeClass( 'left' );

                    if( pos_left + tooltip.outerWidth() > $( window ).width() )
                    {
                        pos_left = target.offset().left - tooltip.outerWidth() + target.outerWidth() / 2 + 20;
                        tooltip.addClass( 'right' );
                    }
                    else
                        tooltip.removeClass( 'right' );

                    if( pos_top < 0 )
                    {
                        var pos_top  = target.offset().top + target.outerHeight();
                        tooltip.addClass( 'top' );
                    }
                    else
                        tooltip.removeClass( 'top' );

                    tooltip.css( { left: pos_left, top: pos_top } )
                        .animate( { top: '+=10', opacity: 1 }, 50 );
                };

                init_tooltip();
                $( window ).resize( init_tooltip );

                var remove_tooltip = function()
                {
                    tooltip.animate( { top: '-=10', opacity: 0 }, 50, function()
                    {
                        $( this ).remove();
                    });

                    target.attr( 'title', tip );
                };

                target.bind( 'mouseleave', remove_tooltip );
                tooltip.bind( 'click', remove_tooltip );
            });
        });
    </script>

    <style>
        .margin-top24{
            margin-top:24px;}
        .hin{
            color: #258FD8 !important;
            border-bottom: dashed 1px;}
        .hin:hover {
            color: rgba(37, 143, 216, 0.65) !important;

        }
    </style>


    <div class="clearfix colelem" id="pu106-6">
        <!-- group -->
        <div style="text-align:center;" class="Heading-H1 clearfix mse_pre_init u106-6"><!-- content -->
            <h2 style="margin-bottom:15px;">
                <span class="animated fadeInUp" style="padding: 0 20px;">How does it <b>work</b></span>
            </h2>


        </div>
    </div>


    <div class="ppage">
        <div style="height:100%;">
            <style>
                .plan-price2 {
                    font-size: 30px;
                    position: relative;
                    display: inline-block;
                    color: #fff;
                    padding: 34px 0px 0px 0;
                }
                .plan-price2 small {
                    display: block;
                    font-size: 18px;
                    line-height: normal;
                    margin-top: 18px;
                    font-weight: 300;
                }
                .dfq li {list-style:circle;}
            </style>
            <div>
                <div class="row margin-bottom48 ">
                    <div class="fnn">


                        <div class="clr"></div>
                        <div class="texts" style="
    padding-bottom: 20px;
">WALK FUNDS is a unique and promising mechanism accessible and cost-effective marketing approach. Which is able to provide long-term earnings prospects, people who are discovering new opportunities, seeking to gain financial well-being.</div><p></p>


                        <p id="a" class="margin-top24"><div style="padding-top: 25px;" class="cabh clr">Unique dynamic INVESTMENT PLAN</div>
                        <hr class="hrz">
                        <div class="texts" style="padding-bottom: 20px;">We offer a uniquely developed three stage system of earnings. The program has 3 short term plans.205% to 720% Investment deposit can work from one to an unlimited number of days. The life of the deposit affects his great interest rate and the final total earnings.</div>

                        <div class="row" style="width:100%; margin:0 auto; "><!-- Pricing table 3 column start -->

                            <!-- plan start -->


                            <div class="col-md-4" style="float: left;">
                                <div class="plan text-center pl1" style="
    height: 155px;  border-radius: 7px;  margin-top: 10px;
">
                                    <span class="plan-name"><b>Plan </b>A</span>
                                    <p class="plan-price2"><span class="plan-price3"><strong><?php echo ($this->planA_daily) ?>% DAILY</strong><small><?php echo ($this->planA_duration) ?> DAYS</small></span></p>

                                </div>
                                <div class="arrowset mrkf fixne"></div>
                            </div>

                            <div class="col-md-4" style="float: left;">
                                <div class="plan text-center pl2" style="
    height: 155px;  border-radius: 7px;  margin-top: 10px;
">
                                    <span class="plan-name"><b>Plan </b>B</span>
                                    <p class="plan-price2"><span class="plan-price3"><strong><?php echo ($this->planB_daily) ?>% DAILY</strong><small><?php echo ($this->planB_duration) ?> DAYS</small></span></p>

                                </div>
                                <div class="arrowset mrkf fixne"></div>
                            </div><div class="col-md-4" style="float: left;">
                                <div class="plan text-center pl3" style="
    height: 155px;  border-radius: 7px;  margin-top: 10px;
">
                                    <span class="plan-name" ><b>Plan C</b></span>
                                    <p class="plan-price2"><span class="plan-price3"><strong><?php echo ($this->planC_daily) ?>% DAILY</strong><small><?php echo ($this->planC_duration) ?> DAYS</small></span></p>

                                </div>
                            </div>

                        </div></p>


                        <div class="row" style="width:100%; margin:0 auto; float: left;"><!-- Pricing table 3 column start -->

                            <!-- plan start -->

                            <p id="a" class="margin-top24"></p><div style="padding-top: 70px;" class="cabh clr">PRINCIPLE OF INVESTMENT PORTFOLIO WITHDRAWALS</div>
                            <hr class="hrz">

                            <div class="texts" style="padding-bottom: 10px;float: left;width:100%;">Withdrawals of the main investments produces from the one day in real time up to instant withdrawals which does not require to wait, it depends on the profit that you received from working deposit.</div>
                            <div class="col-md-4" style="float: left;">
                                <div class="plan text-center pl1" style="
    height: 155px;  border-radius: 7px;  margin-top: 10px;
">
                                    <span class="plan-name">Withdrawals of main investments</span>
                                    <p class="plan-price21"><strong>1 </strong> day<small> Real-time mode</small></p>

                                </div>
                                <div class="arrowset mrkf fixne"></div>
                            </div>

                            <div class="col-md-4" style="float: left;">
                                <div class="plan text-center pl2" style="
    height: 155px;  border-radius: 7px;  margin-top: 10px;  
    background: url(../images/plan3.png), #bce255; /* Old browsers */  
    background: url(../images/plan3.png), -moz-radial-gradient(center, ellipse cover,  #bce255 0%, #51af00 100%); /* FF3.6+ */  background: -webkit-gradient(radial, center center, 0px, center center, 100%, color-stop(0%,#bce255), color-stop(100%,#51af00)); /* Chrome,Safari4+ */  
    background: url(../images/plan3.png), -webkit-radial-gradient(center, ellipse cover,  #bce255 0%,#51af00 100%); /* Chrome10+,Safari5.1+ */  
    background: url(../images/plan3.png), -o-radial-gradient(center, ellipse cover,  #bce255 0%,#51af00 100%); /* Opera 12+ */  
    background: url(../images/plan3.png), -ms-radial-gradient(center, ellipse cover,  #bce255 0%,#51af00 100%); /* IE10+ */  
    background: url(../images/plan3.png), radial-gradient(ellipse at center,  #bce255 0%,#51af00 100%); /* W3C */  
    filter: url(../images/plan3.png), progid:DXImageTransform.Microsoft.gradient( startColorstr='#bce255', endColorstr='#51af00',GradientType=1 ); /* IE6-9 fallback on horizontal gradient */;
    text-shadow: 1px 1px 3px #7AA700;
">
                                    <span class="plan-name" >The Highest Profit</span>
                                    <p class="plan-price2"><strong>Instant</strong><small>Withdrawals of main investments</small></p>

                                </div>
                                <div class="arrowset2 mrkf fixne"></div>
                            </div><div class="col-md-4" style="float: left;">
                                <div class="plan text-center pl3" style="
    height: 155px;  border-radius: 7px;  margin-top: 10px;
    background: url(../images/plan3.png), #ffff4c; /* Old browsers */  
    background: url(../images/plan3.png), -moz-radial-gradient(center, ellipse cover,  #ffff4c 0%, #FFCB00 100%); /* FF3.6+ */  
    background: url(../images/plan3.png), -webkit-gradient(radial, center center, 0px, center center, 100%, color-stop(0%,#ffff4c), color-stop(100%,#ffd30f)); /* Chrome,Safari4+ */  
    background: url(../images/plan3.png), -webkit-radial-gradient(center, ellipse cover,  #FF4C4C 0%,#FF0000 100%); /* Chrome10+,Safari5.1+ */  
    background: url(../images/plan3.png), -o-radial-gradient(center, ellipse cover,  #ffff4c 0%,#FFCB00 100%); /* Opera 12+ */  
    background: url(../images/plan3.png), -ms-radial-gradient(center, ellipse cover,  #ffff4c 0%,#FFCB00 100%); /* IE10+ */  
    background: url(../images/plan3.png), radial-gradient(ellipse at center,  #FFF200 0%,#DB0000 100%); /* W3C */  filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffff4c', endColorstr='#ffd30f',GradientType=1 ); /* IE6-9 fallback on horizontal gradient */;
    text-shadow: 1px 1px 1px #D39100;
">
				        <span class="plan-name" style="
font-size: 16px;
                               ">Batch number ends on <b>0</b></span>
                                    <p class="plan-price2"><strong>Instant</strong><small>Withdrawals of main investments</small></p>

                                </div>
                            </div>

                        </div>

                        <div style="padding-top: 70px;" class="cabh clr">Balance booster that Increases your incomes</div>
                        <hr class="hrz"><div class="texts" style="padding-bottom: 20px;">Earn extra on earned money. As soon as one of your earned money balances exceed $ 10, you immediately begin to receive additional percentage to the daily interest rate called balance booster. Balance booster will be assigned to the balance that stores the required amount to activate balance booster. This bonus program is working at the moment to maintain the balance of money earned a certain level.</div>
                        <div class="row" style="width:100%; margin:0 auto; "><!-- Pricing table 3 column start -->

                            <!-- plan start -->


                            <div class="col-md-4" style="float: left;">
                                <div class="plan text-center balbooster" style="
    height: 155px;  border-radius: 7px;  margin-top: 10px;
">
                                    <span class="plan-name">BALANCE <b><?php echo ($this->planA_amount) ?></b></span>
                                    <p class="plan-price2"><strong><?php echo ($this->planA_profit) ?>%</strong><small> For balance earnings</small></p>

                                </div>
                                <div class="arrowset mrkf fixne"></div>
                            </div>

                            <div class="col-md-4" style="float: left;">
                                <div class="plan text-center balbooster2" style="
    height: 155px;  border-radius: 7px;  margin-top: 10px;
">
                                    <span class="plan-name">BALANCE <b><?php echo ($this->planB_amount) ?></b></span>
                                    <p class="plan-price2"><strong><?php echo ($this->planB_profit) ?>%</strong><small> For balance earnings</small></p>

                                </div>
                                <div class="arrowset mrkf fixne"></div>
                            </div><div class="col-md-4" style="float: left;">
                                <div class="plan text-center balbooster3" style="
    height: 155px;  border-radius: 7px;  margin-top: 10px;
">
                                    <span class="plan-name">BALANCE <b><?php echo ($this->planC_amount) ?></b></span>
                                    <p class="plan-price2"><strong><?php echo ($this->planB_profit) ?>%</strong><small> For balance earnings</small></p>

                                </div>
                            </div>

                        </div>


                        <p id="a" class="margin-top24"><div style="padding-top: 70px;" class="cabh clr">Referral system of EARNINGS</div></p>
                        <hr class="hrz"><div class="texts" style="padding-bottom: 20px;">In system of affiliate earnings includes a multi-level program from contributions of partners. Once your partner from any of three lines will make a deposit, earnings will be added to the section with affiliate panels. Each income is accruing for 24 hours in real-time, from the time of the deposit partner of one of the lines.

                        </div>
                        <div class="row" style="width:100%; margin:0 auto; "><!-- Pricing table 3 column start -->

                            <!-- plan start -->


                            <div class="col-md-4" style="float: left;">
                                <div class="plan text-center affiliates1" style="
    height: 155px;  border-radius: 7px;  margin-top: 10px;
">
                                    <span class="plan-name" ><b>First</b> level</span>
                                    <p class="plan-price2"><strong>+3%</strong><small>From partner <b>deposits</b></small></p>

                                </div>
                            </div>

                            <div class="col-md-4" style="float: left;">
                                <div class="plan text-center affiliates2" style="
    height: 155px;  border-radius: 7px;  margin-top: 10px;
">
                                    <span class="plan-name"><b>Second</b> level</span>
                                    <p class="plan-price2"><strong>+1.5%</strong><small>From partner <b>deposits</b></small></p>

                                </div>
                            </div><div class="col-md-4" style="float: left;">
                                <div class="plan text-center affiliates3" style="
    height: 155px;  border-radius: 7px;  margin-top: 10px;
">
                                    <span class="plan-name"><b>Third</b> level</span>
                                    <p class="plan-price2"><strong>+1%</strong><small>From partner <b>deposits</b></small></p>

                                </div>
                            </div>

                        </div>

                        <div style="padding-top: 70px;" class="cabh clr">INTERACTIVE notifications system</div>
                        <hr class="hrz"><div class="texts" style="padding-bottom: 20px;">
                            <div class="left" style="      z-index: 9999;    background: rgba(35, 35, 35, 0.47) url(images/notofies.png) 8px center no-repeat;  background-size: 26px;  height: 45px;  width: 45px;  border-radius: 35px;  border: 2px solid #fff;  cursor: pointer;
    margin: -7px 13px 0px 0px;
">

                                <span class="popamount">21</span>
                                <a href="#"></a> </div>
                            For a more comfortable and pleasant work, we have developed a system of interactive notifications about actions that happened at the moment and after work in the personal account, list of notifications:<br> <br>

                            <ul class="dfq"><li>New partners that join your structure</li>
                                <li> Affiliate accruals, received from active partners</li>
                                <li> Transition of unique multiplier to a new level</li>
                                <li> Increasing levels of balance boosters</li>
                                <!--<li>Information about maked deposits and payments</li>-->
                                <li>Security (identification IP-address, date of sign in)</li>
                                <li>Closure of worked out positions</li>
                                <!--<li>Summary information about earnings</li>-->
                            </ul><br> This and much more is waiting for you in your personal account. WALK FUNDS. It's your best choice! WALK FUNDS. It's your best choice!</div>


                        <div style="padding-top: 25px;" class="cabh clr">A convenient way to make payments</div>
                        <hr class="hrz"><div class="texts" style="padding-bottom: 20px;">We integrated the most actively used payment systems for a safe and secure work with WALK FUNDS. WALK FUNDS.

                        </div></div>





                </div></div></div></div>

</div>
</div>


</div><!-- column -->
<div class="clearfix"></div>
<div class="osd widj">

    <div class="footer" style="padding-bottom: 25px;"><!-- column -->
        <div class="clearfix" id="u320_align_to_page" style="padding: 20px 0;">

            <div style="display: inline-block;" class="Subheading-White clearfix colelem" id="u825-4"><!-- content -->
                <span style="display:inline-block; font-size: x-large">Accepting payment systems with
                        <img src='../templates/images/bt.png' style="width: 75px; height:25px;">
                    </span>
                <!--                <div style="padding: 22px 0px 0 140px;">-->
                <!--                    <div style="background:url('../templates/images/pm.png') no-repeat; width: 171px; height:50px;float:left;padding-right: 70px;"></div>-->
                <!--                    <div style="background:url('../templates/images/bt.png') no-repeat; width: 129px; height:50px;"></div>-->
                <!--                    <div style="background:url('../templates/images/pe.png') no-repeat; width: 253px; height:50px;float:left;top: 3px;position: relative;"></div>-->
                <!--                </div>-->
            </div>
        </div>
    </div>
    <div style="margin-top: -37px;"><!-- column -->
        <footer>

            <div class="footero">
                <div class="contain">
                    <div class="stpnw"><img width="170" src="templates/images/logo.png" class="instq"> © 2017
                    </div>
                    <div class="fixtd3">

                        <div style="padding: 2px 0px;"><a href="/" class="footerlink">Home</a></div>
                        <div style="padding: 2px 0px;"><a href="aboutus" class="footerlink">About us</a></div>
                        <div style="padding: 2px 0px;"><a href="support" class="footerlink">Feedback</a></div>

                    </div>



                    <div class="fixtd2">

                        <div style="padding: 2px 0px;"><a href="faq" class="footerlink">FAQ</a></div>
                        <div style="padding: 2px 0px;"><a href="terms" class="footerlink">Terms of use</a></div>

                    </div><div style=" position:relative; top: 25px; float: left; width: 110px; padding: 0 25px;">
                        <div style="padding: 2px 0px;"><a href="features" class="footerlink">Features</a></div>
                        <div style="padding: 2px 0px;"></div>

                    </div>


                    <div class="fixtd">

                        <div style="padding: 2px 0px;"><a href="#" class="footerlink">Adress: 207 NL. Lincoln Blvd. UK</a></div>
                        <div style="padding: 2px 0px;"><a href="#" class="footerlink">Phone: +447056105150</a></div>
                        <div style="padding: 2px 0px;"><a href="#" class="footerlink">walkfunds.com</a></div>

                    </div>
                </div>
            </div>
        </footer>
    </div>


</div>


</body>
</html>
 
