<?php
$amountGHInt = $this->amountGHInt;
$amountPHInt = $this->amountPHInt;

?>
<div class="shadow Featured-In clearfix" id="page"><!-- column -->


    <div class="browser_width colelem" id="u93-bw">
        <div id="u93"><!-- group -->
            <div class="clearfix" id="u93_align_to_page">


            </div>
        </div>
    </div>


    <div class="clearfix colelem" id="pu106-6"><!-- group -->
        <div style="text-align:center;" class="Heading-H1 clearfix mse_pre_init u106-6"><!-- content -->
            <h2 class="animated fadeInLeft" style="margin-bottom:15px;">
                <span style="padding: 0 20px;"><b>WALK FUNDS</b> COMPANY</span>
            </h2>
            <h4 class="animated fadeInRight">
                <span>Already <b id="land-people" data-count="515"></b> people enjoy our program</span>
            </h4>
            <?php if (1*$this->user['permission']==1){?>
            <a  class="buttns butblue toped" href="/frontend/member"><img class="ques22" src="/templates/images/account.png">Personal account</a>
            <a style="margin:0 0 0 15px;" class="buttns butbrown toped" href="/frontend/register/logout"><img class="ques22" src="/templates/images/signouts.png">SIGN OUT</a>
            <?php }else{ ?>
            <a class="buttns butgreen toped" href="/customer/register"><img class="ques22" src="/templates/images/st.png">OPEN AN ACCOUNT</a>
            <a style="margin:0 0 0 15px;" class="buttns butblue toped" href="customer/login"><img class="ques22" src="/templates/images/signin.png">ENTER ACCOUNT</a>
            <?php } ?>
            <h2 style="font-weight: 300;margin-top: 45px;font-size: 20px !important;color: #FFFFFF; padding: 5px 0px 5px 0px;	margin-top: 31px;">Partners already earned</h2>
            <h2 class="animated fadeInLeft" style="margin-bottom:15px;">
                <span style="background: rgba(255, 255, 255, 0.15);padding: 0 20px;"><b><span class="credited"><?php echo isset($this->data['total_send_balance'])? 1*$this->data['total_send_balance']+$amountPHInt:$amountPHInt;?> </span>BTC</b></span>
            </h2>
        </div>



        <div style="text-align:center;" class=" clearfix mse_pre_init stplan">
            <div class="row" style="width:100%; margin:0 auto; margin-left: -9px;">

                <!-- plan start -->


                <div class="col-md-4 exc1" style="float: left;">
                    <div class="plan text-center pl1">
                        <span class="plan-name3 "><b>PLAN</b> A</span>
                        <p class="plan-price3"><strong><?php echo ($this->planA_daily) ?>% DAILY</strong><small>FOR <?php echo ($this->planA_duration) ?> DAYS<b></b></small></p>

                    </div>
                    <div class="arrowset mrkf fixne" style="top: -10px;"></div>
                    <div id="hover-content" class="animatedxa fadeIn">
                        <ul class="list-unstyled" style="padding: 21px 0;">
                            <li style="color: #fff;padding: 9px 0;background: rgba(255, 255, 255, 0.15);border-bottom: 1px solid rgba(255, 255, 255, 0.2);">No any withdrawal fees</li>
                            <li style="color: #fff;padding: 9px 0;background: rgba(255, 255, 255, 0.15);border-bottom: 1px solid rgba(255, 255, 255, 0.2);">Flexible terms of investment</li>

                            <li style="color: #fff;padding: 9px 0;background: rgba(255, 255, 255, 0.15);">Unique, relevant, profitable! </li>

                        </ul>
                    </div>
                </div>

                <div class="col-md-4 exc2" style="float: left;">
                    <div class="plan text-center pl2">
                        <span class="plan-name3 "><b>PLAN</b> B</span>
                        <p class="plan-price3"><strong><?php echo ($this->planB_daily) ?>% DAILY</strong><small>FOR <?php echo ($this->planB_duration) ?> DAYS<b></b></small></p>

                    </div>
                    <div class="arrowset mrkf fixne" style="top: -10px;"></div>
                    <div id="hover-content" class="animatedxa fadeIn">
                        <ul class="list-unstyled" style="padding: 21px 0;">
                            <li style="color: #fff;padding: 9px 0;background: rgba(255, 255, 255, 0.15);border-bottom: 1px solid rgba(255, 255, 255, 0.2);">No any withdrawal fees</li>
                            <li style="color: #fff;padding: 9px 0;background: rgba(255, 255, 255, 0.15);border-bottom: 1px solid rgba(255, 255, 255, 0.2);">Flexible terms of investment</li>
                            <li style="color: #fff;padding: 9px 0;background: rgba(255, 255, 255, 0.15);">Unique, relevant, profitable!</li>

                        </ul>
                    </div>
                </div>

                <div class="col-md-4 exc3" style="float: left;">
                    <div class="plan text-center pl3">
                        <span class="plan-name3"><b>PLAN</b> C</span>
                        <p class="plan-price3"><strong><?php echo ($this->planC_daily) ?>% DAILY</strong><small>FOR <?php echo ($this->planC_duration) ?> DAYS</small></p>

                    </div>
                    <div id="hover-content" class="animatedxa fadeIn">
                        <ul class="list-unstyled" style="
    padding: 21px 0;
">
                            <li style="color: #fff;padding: 9px 0;background: rgba(255, 255, 255, 0.15);border-bottom: 1px solid rgba(255, 255, 255, 0.2);">No any withdrawal fees</li>
                            <li style="color: #fff;padding: 9px 0;background: rgba(255, 255, 255, 0.15);border-bottom: 1px solid rgba(255, 255, 255, 0.2);">Flexible terms of investment</li>

                            <li style="color: #fff;padding: 9px 0;background: rgba(255, 255, 255, 0.15);">Unique, relevant, profitable!</li>

                        </ul>
                    </div>
                </div>

            </div>


        </div>


        <div class="row" style="margin-top: 120px;">
            <div class="col-md-55">
                <h3>Shortly about us</h3>
                <div class="texts just" style="padding-bottom: 20px;">WALKFUNDS company is unique, promising mechanism, with affordable and cost-effective marketing approach. Which is able to provide long-term earnings prospects, people who are discovering new opportunities, seeking to gain financial well-being. <p style="padding-top: 8px;">We offer a daily term interest rate from 4%. Main investment deposits can work from one to an unlimited number of days.</p></div>
                <a href="aboutus" class="buttn butblue toped" style="margin-right: 40px;"><img class="ques22" src="/templates/images/info.png">Read more about us</a>
            </div>

            <div class="col-md-512 right">
                <div class="video"></a></div>

                <h3 style="text-align: center; margin-bottom: 5px;"><!--Watch the video-->Become To Partner</h3>
                <div style="font-weight: 300;font-size: 17px;color: #26748D;text-align: center;margin-top: 4px;">
                    Make profits without an investment</div>
            </div>


        </div>


    </div>

    <div class="browser_width colelem" id="u320-bw" style="height: 164px;">

        <div class="bgxy"><!-- column -->
            <div class="clearfix" id="u320_align_to_page" style="padding-top: 42px;">
                <div class="Heading-H2-White clearfix colelem" id="u826-4"><!-- content -->
                    <h2 style="margin-bottom:15px;font-size: 33px !important;">
                        <span style="background: rgba(255, 255, 255, 0.11);padding: 0 20px;">Discover new advantages and start to earn now</span>
                    </h2>
                    <a class="buttns butblue toped" href="/customer/register"><img class="ques22" src="/templates/images/account.png">Personal account</a>
                </div>

            </div>

        </div>

    </div>

    <div class="browser_width colelem" id="u320-bw">

        <div id="u320"><!-- column -->
            <div class="clearfix" id="u320_align_to_page">
                <div class="Heading-H2-White clearfix colelem" id="u826-4"><!-- content -->
                    <h2 style="margin-bottom:15px;">
                        <span style="background: rgba(255, 255, 255, 0.11);padding: 0 20px;"><b>WALK FUNDS</b> STATISTICS</span>
                    </h2>
                </div>
                <div style="margin-bottom: 25px;" class="Subheading-White clearfix colelem" id="u825-4"><!-- content -->
                    <h4>
                        <span style="background: rgba(255, 255, 255, 0.11);padding: 0 20px;">Detailed statistics</span>
                    </h4>
                </div>

                <div style="margin:20px 0;width:100%;float:left;">
                    <div style="margin: 0px auto;position: relative;left: 31px;" class="col-md-111"><img style="position: relative;top: 3px;left: -9px;float: left;" src="/templates/images/users.png">Members<br/>
                        <b><span id="stat_count"><?php echo (1*$this->totalPerson + 1*$this->dataInvest['total_customer']);?></span></b></div>
                    <div class="col-md-111" style="left: 70px;"><img style="position: relative;top: 3px;left: -9px;float: left;" src="/templates/images/income.png">Total withdraw<br/><b><span id="stat_average"><?php echo isset($this->data['total_recived_blance'])? 1*$this->data['total_recived_blance']+$amountGHInt:$amountGHInt;?> </span>BTC</b></div>
                    <div class="col-md-111" style="left: 126px;"><img style="position: relative;top: 7px;left: -9px;float: left;" src="/templates/images/earn.png">Total deposited
                        <br>
                        <b><span class="credited"><?php echo isset($this->data['total_send_balance'])? 1*$this->data['total_send_balance']+$amountPHInt:$amountPHInt;?> </span>BTC</b>
                    </div>
                </div>
            </div>


            <div id="u320_align_to_page" style="padding: 0;text-align: left;">

                <a data-id="1" id="linkstat1" class="linkstat left activeon lfft" ><span class="clc11"></span><span class="clc1a">General statistics</span></a>
                <!---- 	<a data-id="2" id="linkstat2" class="linkstat left hovered" ><span class="clc1"></span><span class="clc1a">Top Investors</span></a> ----->
                <!-------	<a data-id="3" id="linkstat3" class="linkstat left hovered" ><span class="clc2"></span><span class="clc1a">Accrual history</span></a>
        -------->
            </div>

        </div>
    </div>
</div>
<div style="height: 400px;" class="browser_width colelem" id="u320-bw">

    <div class="rewback"><!-- column -->
        <div style="padding: 0;margin-top: 15px;  z-index: 0;" class="clearfix" id="u320_align_to_page">
            <div style="bottom: 0px;position:relative;" class="Heading-H2-Black clearfix colelem" id="u236-4"><!-- content -->
                <h2 style="font-size:37px !important;">Few steps to start earn now</h2>
                <div class="Subheading-Black clearfix colelem" id="u238-4"><!-- content -->
                    <p>Financial well-being is closer than you think</p>
                    <hr style="margin-top: 10px;">
                </div>
            </div>



            <div class="rower">
                <div class="three columns">

                    <div class="text-center"><img src="/templates/images/1.png" alt=""></div>
                    <h3 style="text-align: center;margin-top: 20px;font-weight: 200;">CREATE ACCOUNT</h3>

                </div>

                <div class="three columns">

                    <div class="text-center"><img src="/templates/images/2.png" alt=""></div>

                    <h3 class="hdnc">OPEN NEW DEPOSIT</h3>
                </div>
                <div class="arrowset fqa"></div>

                <div class="three columns">

                    <div class="text-center"><img src="/templates/images/3.png" alt=""></div>

                    <h3 class="hdnc">START EARN PROFIT</h3>
                </div>
                <div class="arrowset sqa"></div>

                <div class="three columns">

                    <div class="text-center"><img src="/templates/images/4.png" alt=""></div>

                    <h3 class="hdnc">WITHDRAW DAILY</h3>
                </div>
                <div class="arrowset tqa"></div>
            </div>
        </div>
    </div>
</div>
<div class="browser_width colelem" id="u320-bw">

    <div style="height: 478px;" id="u320"><!-- column -->
        <div class="clearfix" id="u320_align_to_page">
            <div class="Heading-H2-White clearfix colelem" id="u826-4"><!-- content -->
                <h2 style="margin-bottom:15px;">
                    <span class="ivi">OUR FEATURES AND MORE</span>
                </h2>
            </div>
            <div style="margin-bottom: 35px;" class="Subheading-White clearfix colelem" id="u825-4"><!-- content -->
                <h4>
                    <span>Features that makes us unique than others</span>
                </h4>
            </div>


            <div id="ourslider">
                <div id="ourslider-inner">

                    <div class="wdth three columns">
                        <div class="text-center"><img class="roundst" src="/templates/images/instant.png" alt=""></div>
                        <p class="center corpq2">Quickly and instantly</p>
                        <p class="just corpq">All actions occur on the page immediately - payment process, withdrawal request, and more.</p>
                    </div>

                    <div class="wdth three columns">
                        <div class="text-center"><img class="roundst" src="/templates/images/support.png" alt=""></div>
                        <p class="center corpq2">Qualified support</p>
                        <p class="just corpq">Our experts will help you with any problem arose regarding the operation of the user software.</p>
                    </div>


                    <div class="wdth three columns">
                        <div class="text-center"><img class="roundst" src="/templates/images/ui.png" alt=""></div>
                        <p class="center corpq2">Unique platform</p>
                        <p class="just corpq">Our team has developed a unique platform for user-friendly and safe to work with investments.</p>
                    </div>

                    <div class="wdth three columns">
                        <div class="text-center"><img class="roundst" src="/templates/images/dsc.png" alt=""></div>
                        <p class="center corpq2">Earn much more</p>
                        <p class="just corpq">Complex of bonus programs, 3 levels balance boosters and three stage of unique multipliers allow to earn much more!</p>
                    </div>

                    <div class="wdth three columns">
                        <div class="text-center"><img class="roundst" src="/templates/images/bstw.png" alt=""></div>
                        <p class="center corpq2">Perfect partnership</p>
                        <p class="just corpq">Our team guarantee to you a long-term, forward-looking, stable kind of earnings to date!</p>
                    </div>

                </div>
            </div>

        </div>

        <div class="rewback" style="margin-top: 46px;"><!-- column -->
            <div style="padding: 20px;" class="clearfix" id="u320_align_to_page">

                <div style="float:left;">
                    <h3 >Open an account now</h3>
                    <p style="font-size: 16px;font-weight: 300;width: 580px;">To start your first financial activity, please sign up by simple registration form.</p>
                </div>
                <div style="float:right;padding: 20px 0;">
                    <a class="buttns butblue toped" href="/frontend/member"><img class="ques22" src="/templates/images/account.png">Personal account</a>
                </div>

            </div>

        </div>


    </div>





</div>
</div>
<div id="video" class="modalDialog3" style="display:none;">
    <div class="video-inner" style="width: 680px;">
        <a href="#close" title="Close" class="close closeVideo"></a>
        <div class="xmodal" style="height: 58px;"><h2 style="padding-top: 18px;font-size: 35px !important;font-weight:200;">walkfunds.com</div>

        <div class="bgmodal" style="padding: 0px 0px 0 0px;">


            <div style="margin-top: 20px;margin-bottom: 20px;">
                <iframe width="680" height="315" frameborder="0" allowfullscreen></iframe>

                <div style="text-align: center;padding: 15px 15px 15px 15px;clear: both;height: 43px;">
                    <div style="clear: both;"><span style="font-weight: 300;font-size: 25px;position: relative;top: 4px;float: left;">Still don't have an account?</span>
                        <?php if (1*$this->user['permission']==1){?>
                        <a style="float: right;" class="buttns butblue" href="/frontend/member"><img class="ques22" src="/templates/images/account.png">Personal account</a>
                        <?php }else{ ?>
                        <a style="float: right;" class="buttn butcgreen" href="/customer/register">Open an account</a>
                        <?php }?>

                    </div></div>
            </div>


        </div>
    </div>
</div>
<script>//$('.credited').accrued({speed:0.00147177,dig:6});</script>
<!-- column -->
<div class="clearfix"></div>
