<?php
$uri = $this->serverUrl();
?>
<link type="text/css" rel="stylesheet" href="/templates/css/form/backend/sendmoney.css">
<link type="text/css" rel="stylesheet" href="/templates/css/backend_common.css">
<?php $noimage=$this->noimage; ?>
<div class="page-content-admin">
    <div class="message"></div>
    <?php if (1*$this->dataPlan['count_send_day']>0){?>
        <div class='form-group isa_error'><i class='fa fa-times-circle'></i><span style="color: red;"><b>!!!! The number of times has to send money in days : <?php echo $this->dataPlan['count_send_day']; ?></b></span></div>
    <?php } ?>


    <div style="text-align: right"><button class="btn btn-sm label-danger" onclick="sendmoneyTrans()">SEND MONEY NOW</button></div>

    <div><span style="color: red;"><b>PLAN IN CURRENT DAY. Please control your profit!</b></span></div>
    <div class="day-plan-area" style="padding-left: 30px;">
        <div class="row col-md-12">
            <div class="col-md-6">
                <div class="panel panel-blue">
                    <div class="panel-body pan">
                        <!-- REPORT AREA-->
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <tbody>
                                <tr>
                                    <th width="60%">Total Profit Now</th>
                                    <td width="40%">
                                        <?php echo isset($this->dataPlan['total_profit'])? number_format(1*$this->dataPlan['total_profit'], 3, ',', ''):0;?>  BTC
                                    </td>
                                </tr>
                                <tr>
                                    <th width="60%">Plan money send today</th>
                                    <td width="40%">
                                        <?php echo isset($this->dataPlan['plan_money_send'])? number_format(1*$this->dataPlan['plan_money_send'], 3, ',', ''):0;?>  BTC
                                    </td>
                                </tr>
                                <tr>
                                    <th width="60%">Total Profit Remaining</th>
                                    <td width="40%">
                                        <?php echo isset($this->dataPlan['plan_profit'])? number_format(1*$this->dataPlan['plan_profit'], 3, ',', ''):0;?>  BTC
                                    </td>
                                </tr>

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="w-data-table">
        <div class="w-body-table-fix-1 tbl-data-search" >
            <table id="tbl-seach-1" class="tbl-body-1 table-bordered">
                <thead>
                <tr>
                    <th width="30px" rowspan="2">ID</th>
                    <th width="200px">Date</th>
                    <th width="100px"rowspan="2">Remaing day</th>
                    <th width="130px"rowspan="2">User Name</th>
                    <th width="100px"rowspan="2">Phone</th>
                    <th width="100px"rowspan="2">Amount(BTC)</th>
                    <th width="200px">Total Profit (BTC)</th>
                    <th width="120px"rowspan="2">Status</th>
                    <th rowspan="2">Image</th>
                    <th rowspan="2">Active</th>
                    <th width="100px"rowspan="2">Delete</th>
                </tr>
                <tr>
                    <th width="200px" class="boder-top-white">Durations (days)</th>
                    <th width="200px" class="boder-top-white">Profit type</th>
                </tr>
                </thead>
                <tbody>
                <?php if(isset($this->data) && !empty($this->data)){ $i= 0;?>
                    <?php foreach($this->data as $row){ $i++;
                        $filename = $row['image'];
                        $filenameTmp    =   $noimage;
                        if(file_exists($filename)){
                            $handle = fopen($filename, "rb");
                            $filenameTmp    =   $filename;
                        }else{
                            $handle = fopen($noimage, "rb");
                        }
                        $contents = fread($handle, filesize($filenameTmp));
                        fclose($handle);
                        ?>
                        <tr class="tr-record" record-id="<?php echo $row['ID'];?>">
                            <td width="30px" rowspan="2" align="center"><?php echo $row['ID'];?></td>
                            <td width="150px" align="center"><?php echo $row['senddate'];?></td>
                            <td width="70px" rowspan="2" style="text-align: center;"><?php echo $row['remaining_day']?> day</td>
                            <td width="130px" rowspan="2" align="center"><?php echo $row['UserName'];?></td>
                            <td width="100px" rowspan="2" align="center"><?php echo $row['Mobile'];?></td>
                            <td width="100px" rowspan="2" align="center"><?php echo $row['amount'];?></td>
                            <td width="130px" style="text-align: center;"><?php echo $row['bonus'];?>
                               <!-- --><?php
/*                                    if($row['bonus_from'] !=''){
                                        echo '( from f1: '.$row['bonus_from'].')';
                                    }
                                */?>
                            </td>
                            <td width="80px" rowspan="2" class="text-center"><span class="label label-sm <?php echo $row['color'];?>"><?php echo $row['status'];?></span></td>
                            <td rowspan="2" class="image-view text-center"><span class="view-image-btn label label-sm label-info" style="cursor: pointer;">View Image</span>
                                <div class="modal myModal">
                                    <span class="close">&times;</span>
                                    <img class="modal-content img01">
                                    <div class="caption"></div>
                                </div>
                                <img class="myImg" src="data:image;base64,<?php echo base64_encode($contents);?>" style="display: none;">
                            </td>
                            <td rowspan="2" class="text-center"><input type="checkbox" class="active-flg" <?php if($row['active_sendmoney'] == 1){?> checked="checked" <?php } ?>></td>
                            <td rowspan="2" width="50px" class="text-center"><span class="delete-btn label label-sm label-info" style="cursor: pointer; width: 40px;">X</span></td>
                        </tr>
                        <tr class="sub-record" record-id="<?php echo $row['ID'];?>">
                            <td width="150px" style="color: red; text-align: center;"><?php echo $row['duration'];?> days</td>
                            <td width="130px"  style=" <?php if($row['bonus_from_transgh'] !='' && $row['bonus_from_transgh'] !=0){ ?>color: red; <?php } ?> text-align: center;">
                                <?php
                                if($row['bonus_from_transgh'] !='' && $row['bonus_from_transgh'] !=0){
                                    echo 'Bonus from '.$row['bonus_from'];
                                }else{
                                    echo 'Normal';
                                }
                                ?>
                            </td>
                        </tr>
                    <?php } ?>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>


</div>
<script type="text/javascript" src="/templates/js/form/backend/admin_sendmoney.js"></script>
<script type="text/javascript">
    var _countSendInDay = '<?php echo isset($this->dataPlan['count_send_day'])? 1*$this->dataPlan['count_send_day']:0; ?>';

</script>