<?php
$uri = $this->serverUrl();
?>
<style>
    .icon-header{
        height: 60px !important;
    }
    .table-bordered th{
        background: rgba(61, 61, 61, 0.81);
        color: #FFFFFF;
    }
    .myImg {
        border-radius: 5px;
        cursor: pointer;
        transition: 0.3s;
    }

    .myImg:hover {opacity: 0.7;}

    /* The Modal (background) */
    .modal {
        display: none; /* Hidden by default */
        position: fixed; /* Stay in place */
        z-index: 1; /* Sit on top */
        padding-top: 100px; /* Location of the box */
        left: 279px;
        top: 0;
        width: 100%; /* Full width */
        height: 100%; /* Full height */
        overflow: auto; /* Enable scroll if needed */
        background-color: rgb(0,0,0); /* Fallback color */
        background-color: rgba(0,0,0,0.9); /* Black w/ opacity */
    }

    /* Modal Content (image) */
    .modal-content {
        margin: auto;
        display: block;
        width: 80%;
        max-width: 700px;
    }

    /* Caption of Modal Image */
    .caption {
        margin: auto;
        display: block;
        width: 80%;
        max-width: 700px;
        text-align: center;
        color: #ccc;
        padding: 10px 0;
        height: 150px;
    }

    /* Add Animation */
    .modal-content, .caption {
        -webkit-animation-name: zoom;
        -webkit-animation-duration: 0.6s;
        animation-name: zoom;
        animation-duration: 0.6s;
    }

    @-webkit-keyframes zoom {
        from {-webkit-transform:scale(0)}
        to {-webkit-transform:scale(1)}
    }

    @keyframes zoom {
        from {transform:scale(0)}
        to {transform:scale(1)}
    }

    /* The Close Button */
    span.close {
        position: absolute;
        top: 55px;
        right: 35px;
        color: #f1f1f1;
        font-size: 40px;
        font-weight: bold;
        transition: 0.3s;
    }

    span.close:hover,
    span.close:focus {
        color: #bbb;
        text-decoration: none;
        cursor: pointer;
    }
    .w-body-table-fix-1{
        height: 645px !important;
    }

</style>
<link type="text/css" rel="stylesheet" href="/templates/css/backend_common.css">
<?php $noimage=$this->noimage; ?>
<div class="page-content-admin">

    <div class="w-data-table">
        <div class="w-body-table-fix-1 tbl-data-search" >
            <table id="tbl-seach-1" class="tbl-body-1 table-bordered">
                <thead>
                <tr>
                    <th width="50px">#</th>
                    <th width="200px">DEPOSIT DATE</th>
                    <th width="200px">PAYMENT DATE</th>
                    <th width="150px">USERNAME</th>
                    <th width="150px">PHONE</th>
                    <th width="200px">PROFIT (BTC)</th>
                    <th width="100px">STATUS</th>
                    <th>IMAGE</th>
                    <!--<th width="150px">Send Money</th>
                    <th width="50px">Delete</th>-->
                </tr>
                </thead>
                <tbody>
                <?php if(isset($this->data) && !empty($this->data)){ $i= 0;?>
                    <?php foreach($this->data as $row){ $i++;
                        $filename = $row['image'];
                        $filenameTmp    =   $noimage;
                        if(file_exists($filename)){
                            $handle = fopen($filename, "rb");
                            $filenameTmp    =   $filename;
                        }else{
                            $handle = fopen($noimage, "rb");
                        }
                        $contents = fread($handle, filesize($filenameTmp));
                        fclose($handle);
                        ?>
                        <tr>
                            <td width="50px" align="center"><?php echo $row['ID'];?></td>
                            <td width="150px" align="center"><?php echo $row['senddate'];?></td>
                            <td width="150px" align="center"><?php echo $row['admin_senddate'];?></td>
                            <td width="150px" align="center"><?php echo $row['UserName'];?></td>
                            <td width="100px" align="center"><?php echo $row['Mobile'];?></td>
                            <td width="100px" align="center"><?php echo $row['amount'];?></td>
                            <td width="100px" class="text-center"><span class="label label-sm <?php echo $row['color'];?>"><?php echo $row['status'];?></span></td>
                            <td class="image-view text-center"><span class="view-image-btn label label-sm label-info" style="cursor: pointer;">View Image</span>
                                <div class="modal myModal">
                                    <span class="close">&times;</span>
                                    <img class="modal-content img01">
                                    <div class="caption"></div>
                                </div>
                                <img class="myImg" src="data:image;base64,<?php echo base64_encode($contents);?>" style="display: none;">
                            </td>
                            <!--<td width="150px" class="text-center"><span class="confirm-btn label label-sm label-info" style="cursor: pointer;">Send Money</span></td>
                            <td width="50px" class="text-center"><span class="confirm-btn label label-sm label-info" style="cursor: pointer; width: 40px;">X</span></td>-->
                        </tr>
                    <?php } ?>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>


</div>
<script>
    $(document).ready(function() {
        try {
            $(document).on('click','.view-image-btn',function(){
                var parent = $(this).parents('td.image-view');
                var modal = $(parent).find('.myModal');
                var img = $(parent).find('.myImg');
                var modalImg = $(parent).find(".img01");
                var captionText = $(parent).find(".caption");
                $(modal).css('display' , "block");
                $(modalImg).attr('src',$(img).attr('src'));
                //captionText.innerHTML = this.alt;
                // Get the <span> element that closes the modal
                var span = $(parent).find("close");
            });
            $(document).on('click','span.close',function(){
                var parent = $(this).parents('td.image-view');
                var modal = $(parent).find('.myModal');
                $(modal).css('display' , "none");
            });

        } catch (e) {
            alert('ready' + e.message);
        }
    });

</script>