<div class="page-content">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-blue">
                <div class="panel-heading">Send Ticket Support</div>
                <div class="panel-body pan">
                    <form method="post" action="/frontend/member/contactadmin">
                        <div class="table-responsive">
                            <?php if(isset($this->successMessage)){?>
                                <div class="form-group isa_success">
                                    <i class="fa fa-times-circle"></i>
                                    <?php echo $this->successMessage; ?>
                                </div>
                            <?php }?>
                            <?php if(isset($this->errorMessage)){?>
                                <div class="form-group isa_error">
                                    <i class="fa fa-times-circle"></i>
                                    <?php echo $this->errorMessage; ?>
                                </div>
                            <?php }?>
                            <table class="table table-hover table-bordered">
                                <tbody>
                                    <tr>
                                        <td colspan="2">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td style="padding-left:20px;">UserName</td>
                                        <td><input type="text" class="form-control" name="username" required="" value="Administrator" readonly=""></td>
                                    </tr>
                                    <tr>
                                        <td style="padding-left:20px;">Email</td>
                                        <td><input type="text" class="form-control" name="email" required="" value="admin@gmail.com" readonly=""></td>
                                    </tr>
                                    <tr>
                                        <td style="padding-left:20px;">Messages</td>
                                        <td><textarea type="text" class="form-control" required="" name="comments"><?php echo isset($this->comment)?$this->comment:''; ?></textarea></td>
                                    </tr>

                                    <tr>
                                        <td colspan="2" style="text-align:center;">
                                            <button type="submit" class="btn btn-info">Send Ticket
                                            </button></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>