<div class="page-content">
    <div style="background: transparent; border: 0; box-shadow: none !important" class="tab-content pan mtl mbn responsive">
        <div id="tab-form-actions" class="tab-pane fade active in">
            <div class="row">

                <div class="col-lg-12">
                    <div class="panel panel-blue">
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-hover table-bordered" style="width: 95%">
                                    <thead>
                                    <tr>
                                        <th class="inheader" width="10%" style="text-align: center">#</th>
                                        <th class="inheader" width="30%" style="text-align: center">DATE</th>
<!--                                        <th>BTC Wallet</th>-->
                                        <th class="inheader" width="30%" style="text-align: center">AMOUNT</th>
                                        <th class="inheader" width="20%" style="text-align: center">LEVEL</th>
                                        <th class="inheader" width="10%" style="text-align: center">STATE</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php if(isset($this->data) && !empty($this->data)){ $i= 0;?>
                                    <?php foreach($this->data as $row){ $i++;
                                    ?>
                                    <tr>
                                        <td class="item" style="text-align: center"><?php echo $i;?></td>
                                        <td class="item" style="text-align: center"><?php echo $row['senddate'];?></td>
                                        <td class="item" style="text-align: center"><?php echo number_format($row['amount'], 3, ',', '');?></td>
                                        <td class="item" style="text-align: center"><?php echo $row['level'];?></td>
                                        <td class="item" style="text-align: center"><span class="label label-sm label-blue <?php echo $row['color'];?>"><?php echo $row['issuccess'];?></span></td>

                                    </tr>
                                        <?php } ?>
                                    <?php } ?>
                                    </tbody>
                                </table>
                                <br><br>
                            </div></div></div>
                </div>
            </div>
            <!--END PAGE WRAPPER--></div>
    </div>
</div>