
<link type="text/css" rel="stylesheet" href="/templates/css/form/frontend/investstatus.css">
<?php $noimage=$this->noimage; ?>
    <div class="page-content">
    <div style="background: transparent; border: 0; box-shadow: none !important" class="tab-content pan mtl mbn responsive">
        <div id="tab-form-actions" class="tab-pane fade active in">
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-blue">
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-hover table-bordered" width="95%">
                                    <thead>
                                    <tr>
                                        <th class="inheader" width="10%" style="text-align: center">#</th>
                                        <th class="inheader" width="20%" style="text-align: center">DATE</th>
                                        <th class="inheader" width="10%" style="text-align: center">SPIN (days)</th>
                                        <th class="inheader" width="10%" style="text-align: center">AMOUNT (BTC)</th>
                                        <th class="inheader" width="20%" style="text-align: center">TOTAL PROFIT (BTC)</th>
                                        <th class="inheader" width="15%" style="text-align: center">STATUS</th>
                                        <th class="inheader" width="15%" style="text-align: center">IMAGE</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                        <?php if(isset($this->data) && !empty($this->data)){ $i= 0;?>
                                        <?php foreach($this->data as $row){ $i++;
                                                $filename = $row['image'];
                                                $filenameTmp    =   $noimage;
                                                if(file_exists($filename)){
                                                    $handle = fopen($filename, "rb");
                                                    $filenameTmp    =   $filename;
                                                }else{
                                                    $handle = fopen($noimage, "rb");
                                                }
                                                $contents = fread($handle, filesize($filenameTmp));
                                                fclose($handle);
                                                ?>
                                        <tr>
                                            <td class="item" style="text-align: center"><?php echo $i;?></td>
                                            <td class="item" style="text-align: center"><?php echo $row['senddate'];?></td>
                                            <td class="item" style="text-align: center"><?php echo $row['duration'];?> days</td>
                                            <td class="item" style="text-align: center"><?php echo $row['amount'];?></td>
                                            <td class="item" style="text-align: center"><?php echo $row['bonus'];?></td>
                                            <td class="item" style="text-align: center"><span class="label label-sm <?php echo $row['color'];?>"><?php echo $row['status'];?></span></td>
                                            <td style="text-align: center" class="image-view item" width="60px"><span class="view-image-btn label label-sm label-info" style="cursor: pointer;">View Image</span>
                                                <div class="modal myModal">
                                                    <span class="close">&times;</span>
                                                    <img class="modal-content img01">
                                                    <div class="caption"></div>
                                                </div>
                                                <img class="myImg" src="data:image;base64,<?php echo base64_encode($contents);?>" style="display: none;">
                                            </td>
                                        </tr>
                                            <?php } ?>
                                        <?php } ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>


                </div>
                <br/><br/>
                <!--END CONTENT--><!--BEGIN FOOTER-->

                <!--END FOOTER--></div>
            <!--END PAGE WRAPPER--></div>
    </div>

</div>
<script>
    $(document).ready(function() {
        try {
            $(document).on('click','.view-image-btn',function(){
                var parent = $(this).parents('td.image-view');
                var modal = $(parent).find('.myModal');
                var img = $(parent).find('.myImg');
                var modalImg = $(parent).find(".img01");
                var captionText = $(parent).find(".caption");
                $(modal).css('display' , "block");
                    $(modalImg).attr('src',$(img).attr('src'));
                    //captionText.innerHTML = this.alt;
                // Get the <span> element that closes the modal
                var span = $(parent).find("close");
            });
            $(document).on('click','span.close',function(){
                var parent = $(this).parents('td.image-view');
                var modal = $(parent).find('.myModal');
                $(modal).css('display' , "none");
            });

        } catch (e) {
            alert('ready' + e.message);
        }
    });

</script>