
<div id="cab_content" style="position: relative;">
<!--ajax-->

<div id="listActiveDeposits" class="listdeposits " style="padding-top: 50px;">
<style>
.rotateit {
    -webkit-animation-name: spin;
    -webkit-animation-duration: 10000ms;
    -webkit-animation-iteration-count: infinite;
    -webkit-animation-timing-function: linear;
    -moz-animation-name: spin;
    -moz-animation-duration: 9000ms;
    -moz-animation-iteration-count: infinite;
    -moz-animation-timing-function: linear;
    -ms-animation-name: spin;
    -ms-animation-duration: 10000ms;
    -ms-animation-iteration-count: infinite;
    -ms-animation-timing-function: linear;

    animation-name: spin;
    animation-duration: 10000ms;
    animation-iteration-count: infinite;
    animation-timing-function: linear;
	 -webkit-transform-origin: center center;
  -ms-transform-origin: center center;
  -o-transform-origin: center center;
  transform-origin: center center;
}

@-ms-keyframes spin {
    from { -ms-transform: rotate(0deg); }
    to { -ms-transform: rotate(360deg); }
}
@-moz-keyframes spin {
    from { -moz-transform: rotate(0deg); }
    to { -moz-transform: rotate(360deg); }
}
@-webkit-keyframes spin {
    from { -webkit-transform: rotate(0deg); }
    to { -webkit-transform: rotate(360deg); }
}
@keyframes spin {
    from {
        transform:rotate(0deg);
    }
    to {
        transform:rotate(360deg);
    }
}
</style>

<div class="hellopic rotateit"></div>
<img src="/templates/images/pulselogo.png" class="left pulselogo">
<div class="left lines"><h3 style="padding: 4px 15px 0px 0px;margin-bottom: 12px;">Welcome <?php echo $this->username ?>!</h3>
<div class="blue" style="font-weight: 300;line-height: 21px;">
    Are pleased to welcome to the ranks of walkfunds.com team.  To get started, go to <a class="link9 office_load" href="invest">investment section</a> or click on the button below. For a clearer work with service, please read the following sections -
	<a class="link9" href="../member">Affiliate</a>, <a class="link9" href="../../features">Features</a> and
	<a class="link9" href="../../faq">Frequently Asked Questions</a>. We wish you a pleasant work!
</div>
<div style="text-align:left;padding-top: 17px;font-style: italic;">Administration walkfunds.com</div></div>

<div style="width:100%; text-align:center;">
<a href="/frontend/member/invest" style="margin-top: 20px;width: 345px;" class="office_load buttn butcblue">Make an investment deposit</a>
</div>
</div>

<!--/ajax-->
</div>