
<link type="text/css" rel="stylesheet" href="/templates/css/form/frontend/ticketlist.css">
<?php $noimage=$this->noimage; ?>
    <div class="page-content">
    <div style="background: transparent; border: 0; box-shadow: none !important" class="tab-content pan mtl mbn responsive">
        <div id="tab-form-actions" class="tab-pane fade active in">
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-blue">
                        <div class="panel-body">

                            <div class="table-responsive">
                                <table class="table table-hover table-bordered" style="    width: 95%;">
                                    <thead>
                                    <tr>
                                        <th class="text-center inheader">#</th>
                                        <th class="text-center inheader">SEND DATE</th>
                                        <th class="text-center inheader">QUESTION</th>
                                        <th class="text-center inheader">ANSWER</th>
                                        <th class="text-center inheader">STATUS</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                        <?php if(isset($this->data) && !empty($this->data)){ $i= 0;?>
                                        <?php foreach($this->data as $row){ $i++;?>
                                        <tr>
                                            <td class="text-center item"><?php echo $i;?></td>
                                            <td class="item"><?php echo $row['senddate'];?></td>
                                            <td class="item"><?php echo $row['question'];?></td>
                                            <td class="text-center item"><?php echo $row['answer'];?></td>
                                            <td class="text-center <?php echo $row['color'];?> item"><?php echo $row['status'];?></td>
                                        </tr>
                                            <?php } ?>
                                        <?php } ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>


                </div>
            </div>
            <!--END PAGE WRAPPER--></div>
    </div>

</div>
<script>
    $(document).ready(function() {
        try {
            $(document).on('click','.view-image-btn',function(){
                var parent = $(this).parents('td.image-view');
                var modal = $(parent).find('.myModal');
                var img = $(parent).find('.myImg');
                var modalImg = $(parent).find(".img01");
                var captionText = $(parent).find(".caption");
                $(modal).css('display' , "block");
                    $(modalImg).attr('src',$(img).attr('src'));
                    //captionText.innerHTML = this.alt;
                // Get the <span> element that closes the modal
                var span = $(parent).find("close");
            });
            $(document).on('click','span.close',function(){
                var parent = $(this).parents('td.image-view');
                var modal = $(parent).find('.myModal');
                $(modal).css('display' , "none");
            });

        } catch (e) {
            alert('ready' + e.message);
        }
    });

</script>