<?php
$uri = $this->serverUrl();
?>
<style>
    .success-td{
        color: green;
    }
    .error-td{
        color: red;
    }

</style>
<link type="text/css" rel="stylesheet" href="/templates/css/form/backend/admin_waiting.css">
<link type="text/css" rel="stylesheet" href="/templates/css/backend_common.css">
<?php $noimage=$this->noimage; ?>
<div class="page-content-admin">
    <div class="message"></div>
    <div class="w-data-table">
        <div class="w-body-table-fix-1 tbl-data-search" style="height: 636px;">
            <table id="tbl-seach-1" class="tbl-body-1 table-bordered">
                <thead>
                <tr>
                    <th width="5%" >ID</th>
                    <th width="10%">ACCESS DATE</th>
                    <th width="15%">IP</th>
                    <th width="20%">USER NAME</th>
                    <th width="10%">STATUS</th>
                    <th width="20%">TYPE</th>
                </tr>
                </thead>
                <tbody>
                <?php if(isset($this->data) && !empty($this->data)){ $i= 0;?>
                    <?php foreach($this->data as $row){ $i++;
                        ?>
                        <tr class="tr-record" record-id="<?php echo $row['id'];?>">
                            <td width="5%" align="center"><?php echo $row['id'];?></td>
                            <td width="10%" align="center"><?php echo $row['access_date'];?></td>
                            <td width="15%" align="center"><?php echo $row['ip'];?></td>
                            <td width="20%" align="center"><?php echo $row['user_name'];?></td>
                            <td width="10%" align="center" class="<?php if($row['access_status_int']==1){?>success-td<?php }else {?> error-td <?php }?>"><?php echo $row['access_status'];?></td>
                            <td width="20%" align="center"><?php echo $row['access_type'];?></td>
                        </tr>
                    <?php } ?>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
<?php echo  $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>

</div>