
<!DOCTYPE html>

<html class="html" lang="en-US">
<head>
	<meta http-equiv="Content-type" content="text/html;charset=UTF-8"/>
	<!-- jQuery library -->
	<script src="/templates/js/jquery.2.1.3.min.js" type="text/javascript"></script>
	<!-- CSS -->
	<link rel="stylesheet" type="text/css" href="/templates/css/site_global.css"/>
	<title><?php echo $this->title;?></title>
</head>
<body>
<div class="header-contents"></div>
<div class="page-contents">
	<?php echo $this->layout()->content; ?>
</div>
<div class="footer-contents"></div>
</body>
</html>