<!DOCTYPE html>
<html lang="en">
<head><title>Sign In</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!--Loading bootstrap css-->
	<link type="text/css" href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,800italic,400,700,800">
	<link type="text/css" rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oswald:400,700,300">
	<link type="text/css" rel="stylesheet" href="vendors/jquery-ui-1.10.3.custom/css/ui-lightness/jquery-ui-1.10.3.custom.css">
	<link type="text/css" rel="stylesheet" href="/templates/font-awesome/css/font-awesome.min.css">
	<link type="text/css" rel="stylesheet" href="/templates/css/bootstrap.css">
	<!--Loading style vendors-->
	<link type="text/css" rel="stylesheet" href="/templates/vendors/animate.css/animate.css">
	<link type="text/css" rel="stylesheet" href="/templates/vendors/iCheck/skins/all.css">
	<!--Loading style-->
	<link type="text/css" rel="stylesheet" href="/templates/css/themes/style1/green-blue.css" id="theme-change" class="style-change color-change">
	<link type="text/css" rel="stylesheet" href="/templates/css/style-responsive.css">
	<link type="text/css" rel="stylesheet" href="/templates/css/common.css">
	<link rel="shortcut icon" href="images/favicon.ico">
</head>
<body id="admin-login">
	<div class="page-form">
		<form method="post" action="/backend/home" class="form">
			<div class="header-content"><h1>Log In</h1></div>
			<div class="body-content">
				<?php if(isset($this->errorMessage)){?>
				<div class="form-group isa_error">
					<i class="fa fa-times-circle"></i>
						<?php echo $this->errorMessage; ?>
				</div>
				<?php }?>
				<div class="form-group">
					<div class="input-icon right"><i class="fa fa-user"></i><input type="text" placeholder="Username" name="username" class="form-control"></div>
				</div>
				<div class="form-group">
					<div class="input-icon right"><i class="fa fa-key"></i><input type="password" placeholder="Password" name="password" class="form-control"></div>
				</div>

				<div class="form-group pull-right">
					<button id="login-customer" type="submit" class="btn btn-info">Log In
						&nbsp;<i class="fa fa-chevron-circle-right"></i></button>
				</div>


				<div class="clearfix"></div>
		</form>
	</div>
	<script src="/templates/js/jquery-1.11.0.min.js"></script>
	<script src="/templates/js/jquery-migrate-1.2.1.min.js"></script>
	<script src="/templates/js/jquery-ui.js"></script>
	<!--loading bootstrap js-->
	<script src="/templates/js/bootstrap.min.js"></script>
	<script src="/templates/js/bootstrap-hover-dropdown.js"></script>
	<script src="/templates/js/html5shiv.js"></script>
	<script src="/templates/js/respond.min.js"></script>
	<script src="/templates/js/vendors/iCheck/icheck.min.js"></script>
	<script src="/templates/js/vendors/iCheck/custom.min.js"></script>
	<script src="/templates/js/iCheck/custom.min.js"></script>
	<script src="/templates/js/common.js"></script>
	<!--<script src="/templates/js/form/frontend/login.js"></script>-->
	<script>//BEGIN CHECKBOX & RADIO
		$('input[type="checkbox"]').iCheck({
			checkboxClass: 'icheckbox_minimal-grey',
			increaseArea: '20%' // optional
		});
		$('input[type="radio"]').iCheck({
			radioClass: 'iradio_minimal-grey',
			increaseArea: '20%' // optional
		});
		//END CHECKBOX & RADIO</script>
</body>
</html>