
<!DOCTYPE html>

<html class="html" lang="en-US">
<head>

    <!-- jQuery library -->
    <script src="/templates/assets/js/jquery.2.1.3.min.js" type="text/javascript"></script>
    <script src="/templates/assets/js/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
    <script src="/templates/assets/js/jquery.scrollbar.js"></script>

    <meta http-equiv="Content-type" content="text/html;charset=UTF-8"/>

    <title>WALK FUNDS - Official web page</title>
    <!-- icos -->
    <link href="/templates/images/57.jpg" rel="apple-touch-icon" sizes="57x57"/>
    <link href="/templates/images/114.jpg" rel="apple-touch-icon" sizes="114x114"/>
    <link href="/templates/images/72.jpg" rel="apple-touch-icon" sizes="72x72"/>
    <link href="/templates/images/144.jpg" rel="apple-touch-icon" sizes="144x144"/>
    <link href="/templates/images/60.jpg" rel="apple-touch-icon" sizes="60x60"/>
    <link href="/templates/images/120.jpg" rel="apple-touch-icon" sizes="120x120"/>
    <link href="/templates/images/76.jpg" rel="apple-touch-icon" sizes="76x76"/>
    <link href="/templates/images/152.jpg" rel="apple-touch-icon" sizes="152x152"/>
    <link href="/templates/images/180.jpg" rel="apple-touch-icon" sizes="180x180"/>
    <link href="/templates/images/fav192.jpg" rel="icon" sizes="192x192" type="image/jpg"/>
    <link href="/templates/images/fav160.jpg" rel="icon" sizes="160x160" type="image/jpg"/>
    <link href="/templates/images/fav96.jpg" rel="icon" sizes="96x96" type="image/jpg"/>
    <link href="/templates/images/fav32.jpg" rel="icon" sizes="32x32" type="image/jpg"/>
    <link style="border-radius:4px;" href="apple/fav16.jpg" rel="icon" sizes="16x16" type="image/jpg"/>
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="/templates/css/site_global.css"/>
    <link rel="stylesheet" type="text/css" href="/templates/css/index.css" id="pagesheet"/>
    <link rel="stylesheet" type="text/css" href="/templates/css/my.css" id="pagesheet"/>
    <!--[if lt IE 9]>
    <link rel="stylesheet" type="text/css" href="css/iefonts_index.css?196463317"/>
    <![endif]-->
    <!-- Other scripts -->

    <link href='https://fonts.googleapis.com/css?family=Roboto:900,400,300,100,700&amp;subset=cyrillic-ext,latin' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/templates/css/morris.css">
    <!--[if lt IE 9]>
    <script src="/js/ie.html5.js?4241844378" type="text/javascript"></script>
    <![endif]-->
    <style>
        .clinkedcolors{color:#2B6F98 !important;
            border-bottom:1px dashed #484848;}
    </style>

    <script src="/templates/js/plugin.acc.js" type="text/javascript"></script>
    <script src="/templates/js/plugin.progress.js" type="text/javascript"></script>

    <script src="/templates/js/morris.js"></script>
    <script src="/templates/js/javascript22c1.js?4241844378" type="text/javascript"></script>

    <audio id="audio-notify" controls="controls" preload="auto">
        <source src="audio/notify.html"></source>
        <source src="audio/notify-2.html"></source>
    </audio>


</head>
<body>

<div class="alertb">

    <a href="#" id="notifies" class="alert-o">
        <span class="popamount"><span class="notifycount">0</span></span>
    </a>


    <span id="notifies_block" class="intern" style = "display:none" >


<div class="tooltipy2 bottom in2 poppad">

<div class="bgpop"></div>

<div class="tooltip-inner2">


<div class="nonews">
	<div class="nonews_block">No more notifications</div>
	<img src="../ssl.gstatic.com/s2/oz/images/notifications/jingles_eb4e5306b38f83915d82034fa93390d9/desktop_static_1x.png" alt="*" class="axb m4a"/>
</div>


<div class="yesnews">

<div style="width:100%; text-align: left;margin-bottom: 5px;"><div style="text-transform:uppercase;font-size:13px;font-weight:300;color: #494949;">You have <b><span class="notifycount">0</span></b> new notifications</div>
</div>
<div class="fixedheight scrollbar-inner">







</div>
<a href="#" id="closeall" class="butbut">Close all</a>
</div>
</div>
</div></span>
</div>



<div class="menubgin"><div style="width:940px; margin:0 auto; height:100%;">
        <a id="u107" href="support" style=""></a>

        <div class="bgxs">
            <ul id="langbar">
                <li id="langbar" style="position: relative;height: 40px;" class="drop">

                    <a href="#" class="bgkx"><img style="margin: 0px 8px 0px -6px;" src="/templates/images/en.png">EN</a>

                </li>
            </ul>
        </div>

        <nav class="indiv menuu119"><!-- horizontal box -->
            <ul class="hr">
                <li><a class="selected" href="/">Home</a></li>
                <li><a  href="aboutus">About us</a></li>
                <li><a  href="features">Features</a></li>
                <li><a  href="faq">FAQ</a></li>
                <li><a  href="support">Feedback</a></li>
            </ul>

        </nav>


    </div></div><div class="shadow Featured-In clearfix" id="page">
    <!-- column -->


    <div class="browser_width colelem" id="u93-bw">
        <div class="u92x2"><!-- boxy -->
            <div class="clearfix" id="u93_align_to_page">
                <a class="anchor_item grpelem" id="features"></a>
            </div>
        </div>


        <div style="width:100%;">     </div>
    </div>

    <script src="js/nanobar.js"></script>
    <script>
        var nanobar = new Nanobar();
        nanobar.go(100);
    </script>

    <script>
        $( function()
        {
            var targets = $( '[rel~=tooltip]' ),
                target  = false,
                tooltip = false,
                title   = false;

            targets.bind( 'mouseenter', function()
            {
                target  = $( this );
                tip     = target.attr( 'title' );
                tooltip = $( '<div id="tooltip"></div>' );

                if( !tip || tip == '' )
                    return false;

                target.removeAttr( 'title' );
                tooltip.css( 'opacity', 0 )
                    .html( tip )
                    .appendTo( 'body' );

                var init_tooltip = function()
                {
                    if( $( window ).width() < tooltip.outerWidth() * 1.5 )
                        tooltip.css( 'max-width', $( window ).width() / 2 );
                    else
                        tooltip.css( 'max-width', 340 );

                    var pos_left = target.offset().left + ( target.outerWidth() / 2 ) - ( tooltip.outerWidth() / 2 ),
                        pos_top  = target.offset().top - tooltip.outerHeight() - 20;

                    if( pos_left < 0 )
                    {
                        pos_left = target.offset().left + target.outerWidth() / 2 - 20;
                        tooltip.addClass( 'left' );
                    }
                    else
                        tooltip.removeClass( 'left' );

                    if( pos_left + tooltip.outerWidth() > $( window ).width() )
                    {
                        pos_left = target.offset().left - tooltip.outerWidth() + target.outerWidth() / 2 + 20;
                        tooltip.addClass( 'right' );
                    }
                    else
                        tooltip.removeClass( 'right' );

                    if( pos_top < 0 )
                    {
                        var pos_top  = target.offset().top + target.outerHeight();
                        tooltip.addClass( 'top' );
                    }
                    else
                        tooltip.removeClass( 'top' );

                    tooltip.css( { left: pos_left, top: pos_top } )
                        .animate( { top: '+=10', opacity: 1 }, 50 );
                };

                init_tooltip();
                $( window ).resize( init_tooltip );

                var remove_tooltip = function()
                {
                    tooltip.animate( { top: '-=10', opacity: 0 }, 50, function()
                    {
                        $( this ).remove();
                    });

                    target.attr( 'title', tip );
                };

                target.bind( 'mouseleave', remove_tooltip );
                tooltip.bind( 'click', remove_tooltip );
            });
        });
    </script>

    <style>
        .margin-top24{
            margin-top:24px;}
        .hin{
            color: #258FD8 !important;
            border-bottom: dashed 1px;}
        .hin:hover {
            color: rgba(37, 143, 216, 0.65) !important;

        }
    </style>


    <div class="clearfix colelem" id="pu106-6">
        <!-- group -->
        <div style="text-align:center;" class="Heading-H1 clearfix mse_pre_init u106-6"><!-- content -->
            <h2 style="margin-bottom:15px;"><span class="animated fadeInUp" style="padding: 0 20px;">Sign in</span></h2>


        </div>
    </div>

    <div style="background: url(../templates/images/ilx.jpg) no-repeat left top white;  float: left;  width: 100%;  padding: 143px 0 53px 0px;margin: -103px 0 0 0;">
        <div class="ppage">



            <script language=javascript>
                function checkform() {
                    if (document.mainform.username.value=='') {
                        alert("Please type your username!");
                        document.mainform.username.focus();
                        return false;
                    }
                    if (document.mainform.password.value=='') {
                        alert("Please type your password!");
                        document.mainform.password.focus();
                        return false;
                    }
                    return true;
                }
            </script>






            <div style="position:relative; height:350px;width:100%">
                <div class="blockauth" style="display:block;">
                    <div class="col-md-6" style="border: 1px solid #E8E8E8;border-radius: 3px;padding: 20px 30px;background: #fff;margin-left: 180px;">
                        <form method=post name=mainform onsubmit="return checkform()" action="/frontend/home/">
                            <input type=hidden name=a value='do_login'>
                            <input type=hidden name=follow value=''>
                            <input type=hidden name=follow_id value=''>

                            <div class="cls500">Username:<br/>
                                <input type=text name=username value='' placeholder="Username" maxlength="20"></div>
                            <div class="cls500">Password:<br/>
                                <input type=password name=password value='' placeholder="••••••••••••••••••••" maxlength="20"></div>

                            <input type=submit value="ENTER TO ACCOUNT" class="logbut logbutb">
                            <a class="ind restorepassword"  style="text-decoration:underline;float:right;position: relative;right:30px;top: 15px;" target="_blank" href="/customer/resetpassword">Restore personal data</a>
                        </form>
                    </div>
                    <h2 style="color: #214999;  font-size: 26px;  padding: 0;  };">
                        <span style="font-size: 20px;  line-height: 34px;  color: white;  background: #253550;  background: rgba(37,53,90,0.8);  display: inline-block;  margin-bottom: 1px;  padding: 5px 10px;  white-space: nowrap;">Sign in</span><br>
                        <span style="font-size: 20px;  line-height: 34px;  color: white;  background: #253550;  background: rgba(37,53,90,0.8);  display: inline-block;  margin-bottom: 1px;  padding: 5px 10px;  white-space: nowrap;">and get started</span>

                    </h2>
                </div>

                <div class="blockauth" style="display:none;">
                    <div class="col-md-6" style="border: 1px solid #E8E8E8;border-radius: 3px;padding: 20px 30px;background: #fff;margin-left: 180px;">



                        <form method=post name=forgotform onsubmit="return checkform();">
                            <input type=hidden name=a value="forgot_password">


                            <div class="cls500">Type your username or e-mail:<br/>
                                <input type="text" name="email" value="" placeholder="user@example.com" maxlength="20"/>
                            </div>
                            <div class="cls500">
                                <div></div>
                                <div class="clear"></div>


                            </div>



                            <div>
                                <div class="left">
                                    <div class="alert alert-success" id="restore-success"  style="display: none; width:180px;"></div>
                                    <div>
                                        <input type=submit value="Send access data" class="logbut logbutb">
                                    </div>
                                </div>
                                <div class="left">
                                    <a class="ind restorepassword"  style="text-decoration:underline;float:right;position: relative;  top: 15px;left: 30px" target="_blank" href="#">Restore personal data</a>
                                </div>
                            </div>
                        </form>
                    </div>
                    <h2 style="color: #214999;  font-size: 26px;  padding: 0;  };">
                        <span style="font-size: 20px;  line-height: 34px;  color: white;  background: #253550;  background: rgba(37,53,90,0.8);  display: inline-block;  margin-bottom: 1px;  padding: 5px 10px;  white-space: nowrap;">Section</span><br>
                        <span style="font-size: 20px;  line-height: 34px;  color: white;  background: #253550;  background: rgba(37,53,90,0.8);  display: inline-block;  margin-bottom: 1px;  padding: 5px 10px;  white-space: nowrap;">Restore password</span>

                    </h2>
                </div>
            </div>
        </div>

    </div>
</div>


</div><!-- column -->
<div class="clearfix"></div>
<div class="osd widj">

    <div class="footer" style="padding-bottom: 25px;"><!-- column -->
        <div class="clearfix" id="u320_align_to_page" style="padding: 20px 0;">

            <div style="display: inline-block;" class="Subheading-White clearfix colelem" id="u825-4"><!-- content -->
                    <span style="display:inline-block; font-size: x-large">Accepting payment systems with
                        <img src='/templates/images/bt.png' style="width: 75px; height:25px;">
                    </span>
<!--                <div style="padding: 22px 0px 0 140px;">-->
<!--                    <div style="background:url('../templates/images/pm.png') no-repeat; width: 171px; height:50px;float:left;padding-right: 70px;"></div>-->
<!--                    <div style="background:url('../templates/images/bt.png') no-repeat; width: 129px; height:50px;"></div>-->
<!--                    <div style="background:url('../templates/images/pe.png') no-repeat; width: 253px; height:50px;float:left;top: 3px;position: relative;"></div>-->
<!--                </div>-->
            </div>
        </div>
    </div>
    <div style="margin-top: -37px;"><!-- column -->
        <footer>

            <div class="footero">
                <div class="contain">
                    <div class="stpnw"><img width="170" src="/templates/images/logo.png" class="instq"> © 2017
                    </div>
                    <div class="fixtd3">

                        <div style="padding: 2px 0px;"><a href="/" class="footerlink">Home</a></div>
                        <div style="padding: 2px 0px;"><a href="aboutus" class="footerlink">About us</a></div>
                        <div style="padding: 2px 0px;"><a href="support" class="footerlink">Feedback</a></div>

                    </div>



                    <div class="fixtd2">

                        <div style="padding: 2px 0px;"><a href="faq" class="footerlink">FAQ</a></div>
                        <div style="padding: 2px 0px;"><a href="terms" class="footerlink">Terms of use</a></div>

                    </div><div style=" position:relative; top: 25px; float: left; width: 110px; padding: 0 25px;">
                        <div style="padding: 2px 0px;"><a href="features" class="footerlink">Features</a></div>
                        <div style="padding: 2px 0px;"></div>

                    </div>


                    <div class="fixtd">

                        <div style="padding: 2px 0px;"><a href="#" class="footerlink">Adress: 207 NL. Lincoln Blvd. UK</a></div>
                        <div style="padding: 2px 0px;"><a href="#" class="footerlink">Phone: +447056105150</a></div>
                        <div style="padding: 2px 0px;"><a href="#" class="footerlink">walkfunds.com</a></div>

                    </div>
                </div>
            </div>
        </footer>
    </div>


</div>


</body>
</html>

